"""
Simulation_initBlock.F90 生成器
══════════════════════════

从 GridBuilder 生成等效的 Fortran Simulation_initBlock.F90 源码。

核心逻辑:
  1. 从 GridBuilder.regions 推导出 Fortran 的条件判断逻辑
  2. 生成符合 FLASH 编码规范的 Fortran 代码
  3. 输出可直接编译的 .F90 文件

生成的 .F90 文件结构:
  - 头注释 (NAME, SYNOPSIS, DESCRIPTION, ARGUMENTS)
  - subroutine Simulation_initBlock(blockId)
  - use 声明
  - 变量声明
  - 网格坐标获取
  - 主循环 (do k, do j, do i)
  - 区域判断逻辑
  - 物理量赋值
  - 清理和返回
"""

from pathlib import Path
from typing import Dict, Any, Optional, List, Tuple
import textwrap

from .grid import GridBuilder, Region


def _species_constants_block(species_names: List[str]) -> str:
    """生成 FLASH 物种常量声明块 (含 #ifndef 保护)。

    仅在 Flash.h 未预定义物种常量时使用，顺序与 setup species= 标志一致。
    """
    if not species_names:
        species_names = ["cham", "targ"]
    decls = ", ".join(
        f"{name.upper()}_SPEC = {i + 1}" for i, name in enumerate(species_names)
    )
    return textwrap.dedent(
        f"""\
        #ifndef CHAM_SPEC
          integer :: {decls}
        #endif"""
    )


_F90_TEMPLATE = """!!****if* source/Simulation/SimulationMain/{sim_path}/Simulation_initBlock
!!
!! NAME
!!
!!  Simulation_initBlock
!!
!!
!! SYNOPSIS
!!
!!  call Simulation_initBlock(integer(IN) :: blockID) 
!!                       
!!
!!
!!
!! DESCRIPTION
!!
!!  Initializes fluid data (density, pressure, velocity, etc.) for
!!  a specified block.  Generated by PhySimX BlockGenerator.
!! 
!! ARGUMENTS
!!
!!  blockID -        the number of the block to initialize
!!  
!!
!!
!!***

subroutine Simulation_initBlock(blockId)
  use Simulation_data
  use Grid_interface, ONLY : Grid_getBlkIndexLimits, &
       Grid_getCellCoords, Grid_putPointData,&
                           Grid_getBlkPtr,         &
                           Grid_releaseBlkPtr

  use Driver_interface, ONLY: Driver_abortFlash
{radtrans_use}
  implicit none

#include "constants.h"
#include "Flash.h"

  ! compute the maximum length of a vector in each coordinate direction 
  ! (including guardcells)

  integer, intent(in) :: blockId
  
  integer :: i, j, k, n
  integer :: blkLimits(2, MDIM)
  integer :: blkLimitsGC(2, MDIM)
  integer :: axis(MDIM)
  real, allocatable :: xcent(:), ycent(:), zcent(:)
  real :: tradActual
  real :: rho, tele, trad, tion, zbar, abar
integer :: species
{face_decls}

{species_constants}
   ! get the coordinate information for the current block from the database
  call Grid_getBlkIndexLimits(blockId,blkLimits,blkLimitsGC)

  ! get the coordinate information for the current block from the database
  call Grid_getBlkIndexLimits(blockId,blkLimits,blkLimitsGC)
  allocate(xcent(blkLimitsGC(HIGH, IAXIS)))
  call Grid_getCellCoords(IAXIS, blockId, CENTER, .true., &
       xcent, blkLimitsGC(HIGH, IAXIS))
  allocate(ycent(blkLimitsGC(HIGH, JAXIS)))
  call Grid_getCellCoords(JAXIS, blockId, CENTER, .true., &
       ycent, blkLimitsGC(HIGH, JAXIS))
  allocate(zcent(blkLimitsGC(HIGH, KAXIS)))
  call Grid_getCellCoords(KAXIS, blockId, CENTER, .true., &
       zcent, blkLimitsGC(HIGH, KAXIS))

#if NFACE_VARS > 0
{face_init}
#endif

  !------------------------------------------------------------------------------

  ! Loop over cells and set the initial state
  do k = blkLimits(LOW,KAXIS),blkLimits(HIGH,KAXIS)
     do j = blkLimits(LOW,JAXIS),blkLimits(HIGH,JAXIS)
        do i = blkLimits(LOW,IAXIS),blkLimits(HIGH,IAXIS)

           axis(IAXIS) = i
           axis(JAXIS) = j
           axis(KAXIS) = k

{region_logic}

           call Grid_putPointData(blockId, CENTER, DENS_VAR, EXTERIOR, axis, rho)
           call Grid_putPointData(blockId, CENTER, TEMP_VAR, EXTERIOR, axis, tele)

{if_3t}
           if (NSPECIES > 0) then
              do n = SPECIES_BEGIN,SPECIES_END
                 if (n==species) then
                    call Grid_putPointData(blockID, CENTER, n, EXTERIOR, axis, 1.0e0-(NSPECIES-1)*sim_smallX)
                 else
                    call Grid_putPointData(blockID, CENTER, n, EXTERIOR, axis, sim_smallX)
                 end if
              enddo
           end if

#ifdef BDRY_VAR
           call Grid_putPointData(blockId, CENTER, BDRY_VAR, EXTERIOR, axis, -1.0)
#endif
         enddo
     enddo
  enddo

{face_cleanup}
  deallocate(xcent)
  deallocate(ycent)
  deallocate(zcent)

  return

end subroutine Simulation_initBlock
"""


class BlockGenerator:
    """Simulation_initBlock.F90 生成器。
    
    从 GridBuilder 生成 Fortran 代码。
    
    用法:
        builder = GridBuilder.from_laserslab_1d()
        gen = BlockGenerator(simulation_name="LaserSlab1d_new")
        gen.build(builder)
        gen.save("Simulation_initBlock.F90")
    """
    
    def __init__(
        self,
        simulation_name: str = "LaserSlab",
        sim_path: str = "hello/LaserSlab1d_new",
        use_radtrans: bool = True,
        use_3t: bool = True,
        use_face_vars: bool = False,
        species: Optional[List[str]] = None,
    ):
        """
        Args:
            simulation_name: FLASH 仿真名称 (用于注释)
            sim_path: 在 FLASH 源码树中的路径
            use_radtrans: 是否使用辐射传输 (RadTrans_mgdEFromT)
            use_3t: 是否使用 3T 物理 (FLASH_3T)
            use_face_vars: 是否使用面变量 (MHD)
            species: 物种名列表 (如 ["cham","shld","samp","targ"])，顺序与
                setup species= 标志一致。为 None 时从 builder.regions 推断。
        """
        self.simulation_name = simulation_name
        self.sim_path = sim_path
        self.use_radtrans = use_radtrans
        self.use_3t = use_3t
        self.use_face_vars = use_face_vars
        self.species = species
        
        self._builder: Optional[GridBuilder] = None
        self._generated_code: Optional[str] = None
    
    def build(self, builder: GridBuilder):
        """从 GridBuilder 构建 F90 代码。
        
        Args:
            builder: GridBuilder 实例
        """
        self._builder = builder
        self._generated_code = self._generate(builder)
        return self
    
    # ============================================================
    # 内部生成逻辑
    # ============================================================
    
    def _generate(self, builder: GridBuilder) -> str:
        """内部生成 Fortran 代码."""
        code = _F90_TEMPLATE
        
        # sim_path 替换
        code = code.replace("{sim_path}", self.sim_path)
        
        # RadTrans use 声明
        radtrans_use = "  use RadTrans_interface, ONLY: RadTrans_mgdEFromT\n" if self.use_radtrans else ""
        code = code.replace("{radtrans_use}", radtrans_use)
        
        # Face 变量声明
        if self.use_face_vars:
            face_decls = textwrap.dedent("""\
                real, pointer, dimension(:,:,:,:) :: facexData,faceyData
                #if NDIM > 0
                  real, pointer, dimension(:,:,:,:) :: facezData
                #endif""")
            face_init = textwrap.dedent("""\
                  if (sim_killdivb) then
                     call Grid_getBlkPtr(blockID,facexData,FACEX)
                     call Grid_getBlkPtr(blockID,faceyData,FACEY)
                     if (NDIM>2) call Grid_getBlkPtr(blockID,facezData,FACEZ)
                  endif""")
            face_cleanup = textwrap.dedent("""\
                #if NFACE_VARS > 0
                  if (sim_killdivb) then
                     do k = blkLimits(LOW,KAXIS),blkLimits(HIGH,KAXIS)
                        do j = blkLimits(LOW,JAXIS),blkLimits(HIGH,JAXIS)
                           do i = blkLimits(LOW,IAXIS),blkLimits(HIGH,IAXIS)+1
                              facexData(MAG_FACE_VAR,i,j,k)= 0.0
                           enddo
                        enddo
                     enddo
                     do k = blkLimits(LOW,KAXIS),blkLimits(HIGH,KAXIS)
                        do j = blkLimits(LOW,JAXIS),blkLimits(HIGH,JAXIS)+K2D
                           do i = blkLimits(LOW,IAXIS),blkLimits(HIGH,IAXIS)
                              faceyData(MAG_FACE_VAR,i,j,k)= 0.0
                           enddo
                        enddo
                     enddo
                     if (NDIM>2) then
                        do k = blkLimits(LOW,KAXIS),blkLimits(HIGH,KAXIS)+K3D
                           do j = blkLimits(LOW,JAXIS),blkLimits(HIGH,JAXIS)
                              do i = blkLimits(LOW,IAXIS),blkLimits(HIGH,IAXIS)
                                 facezData(MAG_FACE_VAR,i,j,k)= 0.0
                              enddo
                           enddo
                        enddo
                     endif
                     call Grid_releaseBlkPtr(blockID,facexData,FACEX)
                     call Grid_releaseBlkPtr(blockID,faceyData,FACEY)
                     if (NDIM>2) call Grid_releaseBlkPtr(blockID,facezData,FACEZ)
                  endif
                #endif""")
        else:
            face_decls = ""
            face_init = ""
            face_cleanup = ""
        
        code = code.replace("{face_decls}", face_decls)
        code = code.replace("{face_init}", face_init)
        code = code.replace("{face_cleanup}", face_cleanup)
        
        # 3T 代码段
        if self.use_3t:
            if_3t = textwrap.dedent("""\
            #ifdef FLASH_3T
                       call Grid_putPointData(blockId, CENTER, TION_VAR, EXTERIOR, axis, tion)
                       call Grid_putPointData(blockId, CENTER, TELE_VAR, EXTERIOR, axis, tele)

                       ! Set up radiation energy density:
                       call RadTrans_mgdEFromT(blockId, axis, trad, tradActual)
                       call Grid_putPointData(blockId, CENTER, TRAD_VAR, EXTERIOR, axis, tradActual)
            #endif""")
        else:
            if_3t = ""
        code = code.replace("{if_3t}", if_3t)
        
        # 区域判断逻辑 - 核心部分
        region_logic = self._generate_region_logic(builder)
        code = code.replace("{region_logic}", region_logic)

        # 物种常量块 (优先用显式 species，否则从 regions 推断)
        if self.species:
            species_names = self.species
        else:
            species_names = list(dict.fromkeys(
                r.species for r in builder.regions if r.species
            ))
        code = code.replace(
            "{species_constants}", _species_constants_block(species_names)
        )

        return code
    
    def _generate_region_logic(self, builder: GridBuilder) -> str:
        """从 regions 生成 Fortran 条件判断逻辑。

        支持多物种分层：每个 region 按 x/y/z 范围映射到对应物种常量，
        默认 (未命中任何 region) 回落到 cham (CHAM_SPEC)。
        """
        dim = builder.spec.dim
        lines = []
        indent = "           "

        # 物种列表 (去重，保留顺序)：优先显式 species，否则从 regions 推断，
        # 并确保 cham 作为兜底物种存在
        if self.species:
            species_names = list(dict.fromkeys(self.species))
        else:
            species_names = list(dict.fromkeys(
                r.species for r in builder.regions if r.species
            ))
        if "cham" not in species_names:
            species_names = ["cham"] + species_names

        # 初始化 species = CHAM_SPEC (默认腔室)
        lines.append(f"{indent}species = CHAM_SPEC")
        lines.append("")

        # 生成 if / else-if 条件链 (跳过零宽区域)
        active_regions = [r for r in builder.regions if self._region_has_extent(r)]
        for i, region in enumerate(active_regions):
            condition = self._make_fortran_condition(region, dim)
            sp = region.species.upper() + "_SPEC"
            if i == 0:
                lines.append(f"{indent}if ({condition}) then")
            else:
                lines.append(f"{indent}else if ({condition}) then")
            lines.append(f"{indent}   species = {sp}")
        lines.append(f"{indent}end if")
        lines.append("")

        # 按物种分配物理量
        lines.append(f"{indent}if(species == CHAM_SPEC) then")
        for sp_name in species_names:
            cap = sp_name.capitalize()
            const = sp_name.upper() + "_SPEC"
            if sp_name == "cham":
                lines.append(f"{indent}   rho  = sim_rho{cap}")
                lines.append(f"{indent}   tele = sim_tele{cap}")
                lines.append(f"{indent}   tion = sim_tion{cap}")
                lines.append(f"{indent}   trad = sim_trad{cap}")
            else:
                lines.append(f"{indent}else if (species == {const}) then")
                lines.append(f"{indent}   rho  = sim_rho{cap}")
                lines.append(f"{indent}   tele = sim_tele{cap}")
                lines.append(f"{indent}   tion = sim_tion{cap}")
                lines.append(f"{indent}   trad = sim_trad{cap}")
        lines.append(f"{indent}end if")

        return "\n".join(lines)

    @staticmethod
    def _region_has_extent(region: Region) -> bool:
        """判断区域是否在任一维度有非零宽度。"""
        for rng in (region.x_range, region.y_range, region.z_range):
            if rng:
                lo, hi = rng
                if hi - lo > 1e-30:
                    return True
        return False
    
    def _make_fortran_condition(self, region: Region, dim: int) -> str:
        """生成 Fortran 区域判断条件."""
        parts = []
        
        if region.x_range:
            xlo, xhi = region.x_range
            parts.append(f"xcent(i) >= {self._fmt(xlo)} .and. xcent(i) <= {self._fmt(xhi)}")
        
        if dim >= 2 and region.y_range:
            ylo, yhi = region.y_range
            parts.append(f"ycent(j) >= {self._fmt(ylo)} .and. ycent(j) <= {self._fmt(yhi)}")
        
        if dim >= 3 and region.z_range:
            zlo, zhi = region.z_range
            parts.append(f"zcent(k) >= {self._fmt(zlo)} .and. zcent(k) <= {self._fmt(zhi)}")
        
        return " .and. ".join(parts) if parts else ".false."
    
    def _make_fortran_assignments(self, region: Region, indent: str) -> List[str]:
        """生成 Fortran 赋值语句 (在 if 块内)."""
        return self._make_value_assignments(region, indent)
    
    def _make_value_assignments(self, region: Region, indent: str) -> List[str]:
        """生成物质属性赋值."""
        lines = []
        lines.append(f"{indent}rho  = sim_rho{region.species.capitalize()}")
        lines.append(f"{indent}tele = sim_tele{region.species.capitalize()}")
        lines.append(f"{indent}tion = sim_tion{region.species.capitalize()}")
        lines.append(f"{indent}trad = sim_trad{region.species.capitalize()}")
        return lines
    
    @staticmethod
    def _fmt(val: float) -> str:
        """Fortran 浮点数格式化."""
        abs_val = abs(val)
        if abs_val == 0.0:
            return "0.0"
        elif abs_val < 0.01 or abs_val >= 10000:
            return f"{val:.6e}"
        elif abs_val >= 1:
            return f"{val:.6g}"
        else:
            return f"{val:.6e}"
    
    # ============================================================
    # Public API
    # ============================================================
    
    def save(self, filepath: str):
        """保存生成的 F90 文件。
        
        Args:
            filepath: 输出文件路径
        """
        if self._generated_code is None:
            raise RuntimeError("请先调用 build() 构建代码")
        
        out = Path(filepath)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(self._generated_code, encoding="utf-8", newline="\n")
        return out
    
    def preview(self) -> None:
        """打印生成的 F90 代码."""
        if self._generated_code is None:
            raise RuntimeError("请先调用 build() 构建代码")
        print(self._generated_code)
    
    @property
    def code(self) -> str:
        """获取生成的代码."""
        if self._generated_code is None:
            raise RuntimeError("请先调用 build() 构建代码")
        return self._generated_code
