# -*- coding: utf-8 -*-
"""GROUPS B, D, E, F, G, H — reconnaissance + closure."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tk import *

B = ["Thermos/mat_Mo/Mo_Ideal_Gas", "Thermos/mat_U/U_IdealGas_EOS",
     "Thermos/mat_W/W_Ideal_Gas", "mat_Au/Au_Rosseland_2003POPHammerRosen",
     "mat_Ba/Ba_1987JQSRT_Planck", "mat_Ge/Ge_2002FED_Planck",
     "mat_Be-1.0/BE_eos_i", "mat_DT-1.0/DT_IDEAL_GAS", "mat_Al-1.0/AL_IDEAL_GAS"]
D = ["mat_Al-1.0/41_ieos", "mat_Al-1.0/42_ieos", "mat_C-1.0/511_ieos",
     "mat_C-1.0/Carbon_DLC_ieos_e", "mat_C-1.0/Carbon_DLC_ieos_i",
     "mat_C-1.0/Carbon_Polystyrene_ieos_e", "mat_C-1.0/Carbon_Polystyrene_ieos_i",
     "mat_CELIA/DD_ieos", "mat_CELIA/DT_ieos", "mat_CELIA/CH_ieos",
     "mat_C-1.0/CH_ieos", "CH/CH_ieos", "mat_Ti/422_ieos",
     "mat_Others/CH10Water1/CH10Water1_ieos", "mat_Others/CH10Water2/CH10Water2_ieos"]
E = ["mat_Al-1.0/AL_eos", "mat_Au-1.0/AU_eos", "mat_Au-1.0/AU_eosd",
     "mat_Be-1.0/BE_eos", "mat_Be-1.0/BE_eos_e", "mat_C-1.0/C_EOS",
     "mat_Ti/Ti_eos", "mat_DT-1.0/DT_EOS", "mat_DT-1.0/DT_EOS_e", "mat_DT-1.0/DT_EOS_i"]
F = ["mat_Al-1.0/AL_SIMPLE_PLANCK", "mat_Al-1.0/AL_SIMPLE_ROSSELAND",
     "mat_Au-1.0/AU_SIMPLE_PLANCK", "mat_Au-1.0/AU_SIMPLE_ROSSELAND",
     "mat_Au-1.0/AU_WorkOp_Ross", "mat_Au-1.0/AU_SIMPLE_PLANCK_MG",
     "mat_Be-1.0/BE_SIMPLE_PLANCK", "mat_Be-1.0/BE_PLANCKx03",
     "mat_C-1.0/C_SIMPLE_PLANCK", "mat_C-1.0/C_SIMPLE_ROSSELAND",
     "mat_DT-1.0/DT_SIMPLE_PLANCK", "mat_DT-1.0/DT_SIMPLE_ROSSELAND"]
G = ["mat_Al-1.0/FILELIST", "mat_Al-1.0/LOCK", "mat_Al-1.0/MODINFO",
     "mat_Al-1.0/README", "mat_CELIA/CHECKSUM", "mat_CELIA/FILELIST",
     "mat_CELIA/MODINFO", "mat_CPC/CHECKSUM", "mat_CPC/FILELIST", "mat_CPC/MODINFO",
     "mat_Ti/FILELIST", "ATOMIC/#LEDCOP", "SNOP/### Generated by SNOP",
     "HeatCapacity/Electron-Phonon Coupling and Electron Heat Capacity in Metals at High Electron Temperatures",
     "Ta2O5/Ta2O5_1G_MULTI from unknown source"]
H = ["Ta2O5/Ta2O5_1G_MULTI", "Ta2O5/Ta_1G_MULTI"]


def probe(rel, k=3, show_tok=True):
    p = os.path.join(MAT, rel.replace("/", os.sep))
    if not os.path.isfile(p):
        print(f"  !! MISSING {rel}"); return
    d = raw(p)
    ne = [l.rstrip(b"\r") for l in d.split(b"\n")]
    he = [l for l in ne if l != b""]
    print("-" * 100)
    print(f"  {rel}   bytes={len(d)}  lines={len(ne)}  nonempty={len(he)}")
    from collections import Counter
    print(f"    len histogram: {dict(sorted(Counter(len(l) for l in he).items()))}")
    f, tail = all_tokens(p, 15)
    print(f"    w15 fields={len(f)} leftover={tail!r}")
    for i in range(min(k, len(he))):
        print(f"    L{i} len={len(he[i])} {he[i][:150]!r}")
    if len(he) > 4:
        print(f"    Llast len={len(he[-1])} {he[-1][:150]!r}")


for nm, grp in [("B", B), ("D (ieos)", D), ("E (eos)", E), ("F (tiny)", F), ("G (bookkeeping)", G), ("H (1G_MULTI)", H)]:
    print("\n" + "#" * 110)
    print(f"# GROUP {nm}")
    print("#" * 110)
    for rel in grp:
        probe(rel)
