# -*- coding: utf-8 -*-
"""Confirm the remaining groups: split-line redundancy in D/E, and F/G/H contents."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tk import *

print("#" * 100)
print("# D/E: leftover/residual analysis (is the 15- or 30-char line the file tail?)")
print("#" * 100)
for rel in ["mat_CELIA/DD_ieos", "mat_C-1.0/CH_ieos", "mat_C-1.0/Carbon_DLC_ieos_i",
            "mat_Ti/Ti_eos", "mat_Au-1.0/AU_eos", "mat_Au-1.0/AU_eosd", "mat_C-1.0/C_EOS"]:
    p = os.path.join(MAT, rel.replace("/", os.sep))
    d = raw(p)
    he = [l.rstrip(b"\r") for l in d.split(b"\n") if l.rstrip(b"\r") != b""]
    f, tail = all_tokens(p, 15)
    print(f"  {rel:<40} N15={len(f):>7} tail={tail!r}  firstline_len={len(he[0])} lastline_len={len(he[-1])}")
    print(f"       raw first 120 bytes: {d[:120]!r}")
    print(f"       raw last  120 bytes: {d[-120:]!r}")

print("\n" + "#" * 100)
print("# F: tiny files, full content")
print("#" * 100)
for rel in ["mat_Al-1.0/AL_SIMPLE_PLANCK", "mat_Al-1.0/AL_SIMPLE_ROSSELAND",
            "mat_Au-1.0/AU_SIMPLE_PLANCK", "mat_Au-1.0/AU_SIMPLE_ROSSELAND",
            "mat_Au-1.0/AU_WorkOp_Ross", "mat_Be-1.0/BE_PLANCKx03",
            "mat_C-1.0/C_SIMPLE_PLANCK", "mat_DT-1.0/DT_SIMPLE_PLANCK",
            "mat_Al-1.0/AL_IDEAL_GAS", "mat_Be-1.0/BE_eos_i"]:
    p = os.path.join(MAT, rel.replace("/", os.sep))
    d = raw(p)
    print(f"\n-- {rel} ({len(d)} B)")
    for i, l in enumerate(d.split(b"\n")):
        if l.rstrip(b"\r") != b"":
            print(f"    L{i} len={len(l.rstrip(chr(13).encode()))} {l.rstrip(b'\r')!r}")
            print(f"        tok={tok15(l, 15)}")

print("\n" + "#" * 100)
print("# G: bookkeeping files, full content")
print("#" * 100)
for rel in ["mat_Al-1.0/FILELIST", "mat_Al-1.0/LOCK", "mat_Al-1.0/MODINFO",
            "mat_Al-1.0/README", "mat_CELIA/CHECKSUM", "mat_CELIA/FILELIST",
            "mat_CELIA/MODINFO", "mat_CPC/CHECKSUM", "mat_CPC/FILELIST", "mat_CPC/MODINFO",
            "mat_Ti/FILELIST", "ATOMIC/#LEDCOP", "SNOP/### Generated by SNOP",
            "Ta2O5/Ta2O5_1G_MULTI from unknown source",
            "HeatCapacity/Electron-Phonon Coupling and Electron Heat Capacity in Metals at High Electron Temperatures"]:
    p = os.path.join(MAT, rel.replace("/", os.sep))
    d = raw(p)
    print(f"\n-- {rel} ({len(d)} B) first 400 bytes:")
    print(f"    {d[:400]!r}")

print("\n" + "#" * 100)
print("# H: *_1G_MULTI files (19391 B)")
print("#" * 100)
for rel in ["Ta2O5/Ta2O5_1G_MULTI", "Ta2O5/Ta_1G_MULTI"]:
    p = os.path.join(MAT, rel.replace("/", os.sep))
    d = raw(p)
    he = [l.rstrip(b"\r") for l in d.split(b"\n") if l.rstrip(b"\r") != b""]
    f, tail = all_tokens(p, 15)
    from collections import Counter
    print(f"\n-- {rel} ({len(d)} B) lines={len(he)} N15={len(f)} tail={tail!r}")
    print(f"    len histogram: {dict(sorted(Counter(len(l) for l in he).items()))}")
    for i in range(min(8, len(he))):
        print(f"    L{i} len={len(he[i])} {he[i][:75]!r}")
    print(f"    Llast {he[-1][:75]!r}")
