# -*- coding: utf-8 -*-
"""probe_11_stubs: dump tiny stub files + bookkeeping files + AU_info in FULL."""
import os, json

REPO = r"E:\PhySimX\PhySimX\simulation\flash_test\layer3\flash\flash\input_gen\gen_eos_op"
M = os.path.join(REPO, "src", "Multi1D++Portable20241128", "matter++")
OUT = os.path.join(REPO, ".workbuddy", "tmp", "out_11.txt")

TARGETS = [
    "mat_Au-1.0/AU_SIMPLE_PLANCK",
    "mat_Au-1.0/AU_SIMPLE_ROSSELAND",
    "mat_Au-1.0/AU_SIMPLE_PLANCK_MG",
    "mat_Au-1.0/AU_WorkOp_Ross",
    "mat_Au-1.0/AU_IDEAL_GAS",
    "mat_Au-1.0/AU_info",
    "mat_Au-1.0/AU_eos",
    "mat_Au-1.0/AU_eosd",
    "mat_Au-1.0/AU_op03p",
    "mat_Au-1.0/AU_op03e",
    "mat_Au-1.0/AU_op03r",
    "mat_Au-1.0/AU_op03z",
    "mat_Be-1.0/BE_PLANCKx03",
    "mat_Be-1.0/BE_SIMPLE_PLANCK",
    "mat_Be-1.0/BE_eos_i",
    "mat_Al-1.0/AL_IDEAL_GAS",
    "mat_Al-1.0/AL_SIMPLE_PLANCK",
    "mat_Al-1.0/AL_SIMPLE_ROSSELAND",
    "mat_C-1.0/C_IDEAL_GAS",
    "mat_C-1.0/C_SIMPLE_PLANCK",
    "mat_DT-1.0/DT_IDEAL_GAS",
    "mat_DT-1.0/DT_SIMPLE_PLANCK",
    "mat_CPC/AU_WorkOp_Ross",
    "mat_CPC/BE_PLANCKx03",
    "mat_CPC/CHECKSUM",
    "mat_CPC/FILELIST",
    "mat_CPC/LOCK",
    "mat_CPC/MODINFO",
    "mat_Al-1.0/FILELIST", "mat_Al-1.0/LOCK", "mat_Al-1.0/MODINFO", "mat_Al-1.0/README",
    "mat_Au-1.0/FILELIST", "mat_Au-1.0/LOCK", "mat_Au-1.0/MODINFO", "mat_Au-1.0/README",
    "mat_Be-1.0/FILELIST", "mat_Be-1.0/LOCK", "mat_Be-1.0/MODINFO", "mat_Be-1.0/README",
    "mat_C-1.0/FILELIST", "mat_C-1.0/LOCK", "mat_C-1.0/MODINFO", "mat_C-1.0/README",
    "mat_CELIA/CHECKSUM", "mat_CELIA/FILELIST", "mat_CELIA/LOCK", "mat_CELIA/MODINFO",
    "mat_DT-1.0/FILELIST", "mat_DT-1.0/LOCK", "mat_DT-1.0/MODINFO", "mat_DT-1.0/README",
    "mat_Ti/FILELIST",
    "Thermos/mat_Mo/Mo_Ideal_Gas",
    "Thermos/mat_U/U_IdealGas_EOS",
    "Thermos/mat_W/W_Ideal_Gas",
    "mat_Ba/Ba_1987JQSRT_Planck",
    "mat_Eu/Eu_Planck_1987JQSRT",
    "mat_Ge/Ge_2002FED_Planck",
    "mat_Au/Au_Rosseland_2003POPHammerRosen",
    "ATOMIC/#LEDCOP",
    "SNOP/### Generated by SNOP",
    "Ta2O5/Ta2O5_1G_MULTI",
    "HeatCapacity/Electron-Phonon Coupling and Electron Heat Capacity in Metals at High Electron Temperatures",
]

def dump(p, maxlines=200, maxbytes=None):
    b = open(p, "rb").read()
    if maxbytes: b = b[:maxbytes]
    try: t = b.decode("utf-8")
    except UnicodeDecodeError:
        try: t = b.decode("gbk")
        except UnicodeDecodeError: t = b.decode("latin-1", "replace")
    lines = t.split("\\r\\n" if "\\r\\n" in t else "\\n")
    return len(b), t, lines

buf = []
for rel in TARGETS:
    p = os.path.join(M, rel)
    buf.append("=" * 100)
    if not os.path.exists(p):
        buf.append("MISSING: %s" % rel); continue
    b = open(p, "rb").read()
    try: t = b.decode("utf-8")
    except UnicodeDecodeError:
        try: t = b.decode("gbk")
        except UnicodeDecodeError: t = b.decode("latin-1", "replace")
    lines = t.splitlines()
    buf.append("### %s   bytes=%d  lines=%d" % (rel, len(b), len(lines)))
    buf.append("--- RAW REPR (first 4000 bytes) ---")
    buf.append(repr(b[:4000]) if len(b) <= 4000 else repr(b[:4000]) + "  ...[truncated]")
    buf.append("--- DECODED (first 60 lines) ---")
    for i, ln in enumerate(lines[:60]):
        buf.append("%4d| %s" % (i, ln))
    if len(lines) > 60:
        buf.append("     ...[%d more lines]" % (len(lines) - 60))
    buf.append("")

open(OUT, "w", encoding="utf-8").write("\n".join(buf))
print("written", OUT, len(buf), "lines")
