"""
IONMIX 核心输入生成与运行模块

提供 IONMIXInputGen 类，支持：
- 参数设置
- 输入文件生成
- 单次运行 (run_single)
- 批量运行 (batch_run)
- 自动文件名生成（Z{izgas}_{fracsp}... 规范）
- 输入/输出同目录保存

基于 Computer Physics Communications 56(1989) 259-278
"""

import os
import re
import shutil
import subprocess
import datetime
from typing import Dict, List, Any, Union, Optional


class IONMIXInputGen:
    """
    IONMIX 输入文件生成与运行类
    """

    # IONMIX 可执行程序所在目录（相对于此文件）
    IONMIX_BIN_DIR = os.path.normpath(
        os.path.join(os.path.dirname(__file__), "..", "Ionmix")
    )

    PARAM_DESCRIPTIONS = {
        'ngases': '气体种类数量（最大=10）',
        'izgas': '每种气体元素的原子序数（最大=54）',
        'atomwt': '每种气体元素的原子量（amu）',
        'fracsp': '每种气体元素的相对丰度（按原子数比例）',
        'ntemp': '等离子体温度点数（最大=20）',
        'ndens': '密度点数（最大=20）',
        'ntrad': '辐射温度点数（最大=20）',
        'tplsma': '等离子体温度（eV）',
        'densnn': '原子核数密度（cm⁻³）',
        'trad': '辐射温度（eV）',
        'dlgtmp': '等离子体温度的对数增量',
        'dlgden': '数密度的对数增量',
        'dlgtrd': '辐射温度的对数增量',
        'nptspg': '每个不透明度群的光子能量网格点数',
        'ngrups': '不透明度多群计算的光子能量群数量（最大=50）',
        'nfrqbb': '每个束缚-束缚跃迁附近的光子能量网格点数',
        'grupbd': '不透明度多群计算的光子能量群边界（eV）',
        'dtheat': '比热和电荷态导数计算的温度增量分数',
        'iplot': '绘图文件控制开关（0→无输出；1→格式化输出）',
        'isw': '各种计算选项的控制开关数组'
    }

    ISW_DESCRIPTIONS = {
        1: '用户提供电离势（0→否；1→是）',
        2: '计算不透明度（0→是；1→否）',
        3: '请求调试输出（0→否；1→是）',
        4: '计算热容和dZ/dT（0→是；1→否）',
        5: '复制输入文件到输出文件（0→是；1→否）',
        6: '电离模型（3→完整三体过程；0→插值；1→Saha；2→日冕）',
        8: '输出格式（0→无；1→旧CONRAD；2→SESAME；3→新CONRAD）',
        11: '包含 Δn=0 的束缚-束缚跃迁（0→包含；1→排除）',
        12: '限制离子到基态（0→否；1→是）',
        13: '不透明度群边界指定（0→默认；1→用户指定；2→基于温度）',
        14: '线轮廓类型（0→Voigt；1→Lorentzian）',
        15: '不透明度最大主量子数（默认值 2 表示基态+2；负值表示绝对值）',
        16: '包含双电子复合（0→是；1→否）',
        17: '包含轫致辐射不透明度（0→是；1→否）',
        18: '包含光电离不透明度（0→是；1→否）',
        19: '包含束缚-束缚跃迁（0→是；1→否；2→核心/翼分别计算）',
        20: '包含散射贡献（0→是；1→否）',
        21: '输出eos.cn4（1→是；0→否）',
        22: '自定义温度网格设置',
        23: '自定义密度网格设置',
        24: '控制光子能量网格类型',
        25: '控制是否添加线中心和电离边缘点',
    }

    def __init__(self):
        """初始化生成器"""
        self.parameters = {}
        self.comments = {}
        self.current_example = ""

    def set_parameter(self, name: str, value: Any, index: int = None) -> None:
        """
        设置参数值

        Args:
            name: 参数名称
            value: 参数值
            index: 数组索引（对于数组参数）
        """
        if index is not None:
            key = f"{name}({index})"
        else:
            key = name
        self.parameters[key] = value

        if name in self.PARAM_DESCRIPTIONS:
            desc = self.PARAM_DESCRIPTIONS[name]
            if name == 'isw' and index is not None and index in self.ISW_DESCRIPTIONS:
                desc = f"isw({index}): {self.ISW_DESCRIPTIONS[index]}"
            self.comments[key] = desc

    def set_array_parameter(self, name: str, values: List[Any]) -> None:
        """设置数组参数（1-based 索引）"""
        for i, value in enumerate(values, 1):
            self.set_parameter(name, value, i)

    def set_grupbd(self, boundaries: List[float]) -> None:
        """设置能群边界参数"""
        self.set_parameter('ngrups', len(boundaries) - 1)
        for i, boundary in enumerate(boundaries, 1):
            self.set_parameter('grupbd', boundary, i)

    def clear_parameters(self) -> None:
        """清除所有参数"""
        self.parameters.clear()
        self.comments.clear()
        self.current_example = ""

    def _format_value(self, value: Any) -> str:
        """格式化参数值为字符串"""
        if isinstance(value, float):
            if abs(value) >= 1e4 or (abs(value) < 1e-2 and value != 0):
                return f"{value:.6e}"
            else:
                return f"{value:.6f}"
        elif isinstance(value, int):
            return str(value)
        else:
            return str(value)

    def _get_array_index(self, param_key: str) -> int:
        """提取数组参数的索引用于排序"""
        match = re.search(r'\((\d+)\)', param_key)
        if match:
            return int(match.group(1))
        return 0

    def generate_input(self, output_dir: str) -> str:
        """
        生成 IONMIX 输入文件内容并写入指定目录

        Args:
            output_dir: 输出目录路径（ionmxinp 将写入到此目录）

        Returns:
            str: 生成的输入文件内容
        """
        lines = []
        inputfilename = "ionmxinp"
        lines.append("! IONMIX Input File")
        lines.append("! Generated by Python IONMIXInputGen")
        lines.append("! Based on Computer Physics Communications 56(1989) 259-278")
        lines.append("")

        lines.append("$data")

        param_order = [
            'ngases',
            'izgas', 'atomwt', 'fracsp',
            'ntemp', 'dlgtmp', 'tplsma',
            'ndens', 'dlgden', 'densnn',
            'ntrad', 'trad',
            'nptspg', 'nfrqbb',
            'dtheat',
            'iplot',
            'isw',
            'ngrups', 'grupbd'
        ]

        for param_base in param_order:
            param_keys = [k for k in self.parameters.keys() if k.startswith(param_base)]
            for key in sorted(param_keys, key=lambda x: self._get_array_index(x)):
                value = self.parameters[key]
                formatted_value = self._format_value(value)
                comment = self.comments.get(key, "")
                if comment:
                    lines.append(f"    {key} = {formatted_value}, \t\t\t ! {comment}")
                else:
                    lines.append(f"    {key} = {formatted_value},")

        lines.append("$end")
        lines.append("")
        lines.append("! End of IONMIX input file")

        content = "\n".join(lines)

        os.makedirs(output_dir, exist_ok=True)
        filepath = os.path.join(output_dir, inputfilename)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

        return content

    def _make_basename(self) -> str:
        """
        从当前参数生成文件名 basename

        格式: Z{izgas1:02d}_{fracsp1:.2f}-Z{izgas2:02d}_{fracsp2:.2f}
        """
        ngases = int(self.parameters.get('ngases', 1))
        parts = []
        for i in range(1, ngases + 1):
            z_key = f"izgas({i})"
            f_key = f"fracsp({i})"
            if z_key in self.parameters and f_key in self.parameters:
                z = int(self.parameters[z_key])
                f = float(self.parameters[f_key])
                # 去除末尾的0
                parts.append(f"Z{z:02d}_{f:.2f}")
            else:
                raise KeyError(f"缺少 izgas({i}) 或 fracsp({i}) 参数")
        return "-".join(parts)

    def _copy_ionmix_binaries(self, dest_dir: str) -> None:
        """
        从 IONMIX 工作目录拷贝可执行文件和源码到目标目录。
        如果可执行文件缺失或无法运行，尝试通过 WSL gfortran 编译。

        Args:
            dest_dir: 目标目录
        """
        src_dir = self.IONMIX_BIN_DIR
        files_to_copy = ["abjt_03", "abjt_03.f"]
        for fname in files_to_copy:
            src_path = os.path.join(src_dir, fname)
            if os.path.exists(src_path):
                shutil.copy2(src_path, os.path.join(dest_dir, fname))

        # 检查目标目录中 abjt_03 是否有效
        dest_bin = os.path.join(dest_dir, "abjt_03")
        dest_src = os.path.join(dest_dir, "abjt_03.f")
        needs_compile = False

        if not os.path.exists(dest_bin):
            needs_compile = True
        else:
            # 文件存在但可能不是可执行 ELF（空文件、损坏等）
            if os.path.getsize(dest_bin) == 0:
                needs_compile = True

        if needs_compile and os.path.exists(dest_src):
            print(f"  [*] 编译 abjt_03.f → abjt_03 (WSL gfortran)...")
            try:
                wsl_path = self._win_to_wsl(dest_dir)
                cmd = [
                    "wsl", "--cd", wsl_path,
                    "gfortran", "-o", "abjt_03", "abjt_03.f",
                    "-O2", "-ffixed-line-length-132"
                ]
                result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
                if result.returncode == 0:
                    print(f"  [+] 编译成功")
                    # 设置可执行权限
                    subprocess.run(
                        ["wsl", "--cd", wsl_path, "chmod", "+x", "abjt_03"],
                        capture_output=True
                    )
                else:
                    print(f"  [!] 编译失败 (返回码 {result.returncode})")
                    if result.stderr:
                        print(f"  [!] {result.stderr.strip()[:300]}")
            except Exception as e:
                print(f"  [!] 编译异常: {e}")

    def _clean_output_folder(self, folder_path: str) -> None:
        """
        清理文件夹，只保留指定文件

        Args:
            folder_path: 要清理的文件夹路径
        """
        files_to_keep = {
            "abjt_03",
            "abjt_03.f",
            "ionmxinp",
            "ionmxout",
            "ionmxbug",
        }

        if not os.path.exists(folder_path):
            return

        for item_name in os.listdir(folder_path):
            item_path = os.path.join(folder_path, item_name)

            # 保留指定文件或以 .cn4 结尾的文件
            if item_name in files_to_keep or item_name.endswith("cn4"):
                continue
            try:
                if os.path.isfile(item_path) or os.path.islink(item_path):
                    os.remove(item_path)
                elif os.path.isdir(item_path):
                    shutil.rmtree(item_path)
            except Exception as e:
                print(f"清理 {item_name} 时出错: {e}")

    def _get_timestamp(self) -> str:
        """获取当前时间戳（%Y%m%d_%H%M）"""
        return datetime.datetime.now().strftime("%Y%m%d_%H%M")

    # ================================================================
    #  批量运行骨架
    # ================================================================

    def _dict_to_parameters(self, params_dict: dict) -> None:
        """
        将参数字典还原为内部参数

        支持三种 value 类型:
        - 标量: {'ntemp': 20}
        - 带索引字典: {'izgas': {1: 7, 2: 8}}
        - 列表（用于 grupbd）: {'grupbd': [0.1, 1.0, 10.0]}
        """
        self.clear_parameters()
        for key, value in params_dict.items():
            if key == 'grupbd':
                # 特殊处理能群边界
                self.set_grupbd(value)
            elif isinstance(value, dict):
                # 带索引的数组参数
                self.current_example = params_dict.get('_name', '')
                for idx, val in value.items():
                    self.set_parameter(key, val, idx)
            else:
                # 标量参数
                self.current_example = params_dict.get('_name', '')
                self.set_parameter(key, value)

    @staticmethod
    def _win_to_wsl(win_path: str) -> str:
        """转换 Windows 绝对路径为 WSL 路径"""
        abs_path = os.path.abspath(win_path)
        drive = abs_path[0].lower()
        return f"/mnt/{drive}{abs_path[2:].replace(os.sep, '/')}"

    def _wsl_run(self, work_dir: str) -> subprocess.CompletedProcess:
        """
        通过 WSL 运行 abjt_03（Linux ELF 二进制）
        """
        wsl_path = self._win_to_wsl(work_dir)
        # 先确保可执行权限
        subprocess.run(["wsl", "--cd", wsl_path, "chmod", "+x", "abjt_03"],
                       capture_output=True, text=True)
        cmd = ["wsl", "--cd", wsl_path, "./abjt_03"]
        return subprocess.run(cmd, capture_output=True, text=True, timeout=300)

    @staticmethod
    def _find_missing_ionpot(work_dir: str) -> int:
        """
        在 ionmxout 中查找电离势为 0 的原子序数

        Returns:
            int: 第一个电离势为 0 的原子序数，无则返回 0
        """
        ionmxout = os.path.join(work_dir, "ionmxout")
        if not os.path.exists(ionmxout):
            return 0
        with open(ionmxout) as f:
            for line in f:
                # 匹配 "atomic #  Z" 的行
                if "atomic #" in line:
                    parts = line.strip().split()
                    for p in parts:
                        try:
                            return int(p)
                        except ValueError:
                            continue
                # 匹配 "ionization state =  0         ionization potential =     0.000"
                if "ionization potential" in line and "0.000" in line:
                    # 向前找 izgas — 从 ionmxout 中找 "gas #" 行
                    return 0  # 无法直接确定，交给调用方读取更详细的信息
        return 0

    @staticmethod
    def _find_runtime_error(work_dir: str) -> str:
        """
        从缓存 stderr 日志中查找 Fortran 运行时错误

        Returns:
            str: 错误描述，无则返回 ""
        """
        stderr_path = os.path.join(work_dir, "_stderr.log")
        if os.path.exists(stderr_path):
            with open(stderr_path) as f:
                content = f.read(2000)
                if "Fortran runtime error" in content:
                    idx = content.find("Fortran runtime error")
                    return content[idx:idx+150].strip()
        return ""

    def run_single(self, params_dict: dict, output_base_dir: str) -> str:
        """
        对单个参数字典执行一次完整的 IONMIX 流程

        Args:
            params_dict: 参数字典
            output_base_dir: 输出基础目录

        Returns:
            str: 生成的 .cn4 文件绝对路径
        """
        # 1. 还原参数
        self._dict_to_parameters(params_dict)

        # 2. 确定 basename 和时间戳
        basename = self._make_basename()
        timestamp = self._get_timestamp()
        folder_name = f"{basename}-{timestamp}"

        # 3. 创建独立工作目录
        work_dir = os.path.join(output_base_dir, folder_name)
        os.makedirs(work_dir, exist_ok=True)

        # 4. 拷贝可执行文件
        self._copy_ionmix_binaries(work_dir)

        # 5. 生成 ionmxinp
        self.generate_input(work_dir)

        # 6. 运行 IONMIX（通过 WSL）
        error_log = ""
        try:
            program_path = os.path.join(work_dir, "abjt_03")
            if os.path.exists(program_path):
                result = self._wsl_run(work_dir)
                if result.returncode == 0:
                    pass  # 正常
                else:
                    print(f"  [!] abjt_03 返回码: {result.returncode}")
                    if result.stderr:
                        error_log = result.stderr.strip()
                        if error_log:
                            print(f"  [!] stderr: {error_log[:300]}")
                    # 将 stderr 保存到文件供后续分析
                    if error_log:
                        with open(os.path.join(work_dir, "_stderr.log"), 'w') as ef:
                            ef.write(error_log)
            else:
                print(f"  [!] 未找到可执行文件: {program_path}")
        except subprocess.TimeoutExpired:
            print(f"  [!] abjt_03 运行超时")
        except Exception as e:
            print(f"  [!] 运行异常: {e}")

        # 7. 重命名 eos.cn4，检测 0 字节
        eos_path = os.path.join(work_dir, "eos.cn4")
        cn4_filename = f"{basename}-{timestamp}.cn4"
        cn4_path = os.path.join(work_dir, cn4_filename)
        if os.path.exists(eos_path):
            size = os.path.getsize(eos_path)
            os.rename(eos_path, cn4_path)
            if size > 0:
                print(f"  [+] 输出: {cn4_filename}  ({size:,} bytes)")
            else:
                # 检查 ionmxout 中默认电离势为 0 的原子序数
                missing_iz = self._find_missing_ionpot(work_dir)
                if missing_iz:
                    print(f"  [!] 输出为空: {cn4_filename} (0 bytes)")
                    print(f"  [!] 原因: 元素Z={missing_iz} 无默认电离势，需创建 ATOM{missing_iz:02d}.DAT")
                else:
                    print(f"  [!] 输出为空: {cn4_filename} (0 bytes)，检查 ionmxout")
        else:
            # eos.cn4 未生成 — 检查 ionmxout 中是否有 Fortran 运行时错误
            err_hint = self._find_runtime_error(work_dir)
            if err_hint:
                print(f"  [!] eos.cn4 未生成 — {err_hint}")
            else:
                print(f"  [!] eos.cn4 未生成，检查 ionmxout")
            cn4_path = ""

        # 8. 清理工作目录
        self._clean_output_folder(work_dir)

        return cn4_path

    def batch_run(self, params_list: List[dict], output_base_dir: str) -> List[str]:
        """
        批量执行多个参数字典的 IONMIX 流程

        Args:
            params_list: 参数字典列表
            output_base_dir: 输出基础目录

        Returns:
            List[str]: 生成的 .cn4 文件路径列表
        """
        os.makedirs(output_base_dir, exist_ok=True)
        results = []
        total = len(params_list)
        for i, params_dict in enumerate(params_list, 1):
            name = params_dict.get('_name', f'任务{i}')
            print(f"[{i}/{total}] {name} ...")
            cn4_path = self.run_single(params_dict, output_base_dir)
            results.append(cn4_path)
            print(f"[{i}/{total}] 完成: {cn4_path}")
            print()
        return results
