#!/bin/bash
OBJ="/root/QC/FLASH/FLASHSNB/FLASH4.8/SNBOneCH_ml_ug_obj"
REF="/root/QC/FLASH/FLASHSNB/FLASH4.8/source/Simulation/SimulationMain/SNB_1D_laser/flash.par"
echo "=== OUR: 所有 hypre / eos / newton 键 ==="
grep -nEi 'hypre|eos_max|newton|solver|precond|pc_|reltol|maxiter|smallT|smallt|eos_small' "$OBJ/flash.par"
echo ""
echo "=== REF: 同字段 ==="
grep -nEi 'hypre|eos_max|newton|solver|precond|pc_|reltol|maxiter|smallT|smallt|eos_small' "$REF"
echo ""
echo "=== OUR: eos_nr WARN 统计 ==="
grep -c 'eos_nr WARN' "$OBJ/wsl_run_snbonech.log"
echo "=== 前 3 条 eos_nr WARN ==="
grep -n 'eos_nr WARN' "$OBJ/wsl_run_snbonech.log" | head -3
echo ""
echo "=== OUR: hypre 失败次数 ==="
grep -c 'gr_hypreSolve.*Nonconv' "$OBJ/wsl_run_snbonech.log"
echo ""
echo "=== OUR: 10 群辐射边界 ==="
grep -nE 'rt_mgd.*BoundaryType|rt_mgdFl|rt_useMGD|rt_mgdNumGroups' "$OBJ/flash.par"
