#!/usr/bin/env python3
"""ch_center dual-density comparison - plotting script (PPT-friendly).

Reads result.h5 generated by run_compare.py (density/temperature fields)
and produces:
  1. dens(x) spatial profile comparison at the final time
  2. central dens(t) time evolution comparison
  3. side-by-side x-t density heatmaps

All text is English-only and uses fonts >= 18pt via
`output_processors.plotter.plot_style` (PPT-ready output).

Usage:
  python plot_compare.py                          # default run dir
  python plot_compare.py --runs-dir PATH          # custom run dir
  python plot_compare.py --out PATH               # custom output dir
"""

import argparse
import json
import sys
from pathlib import Path

import numpy as np

# ── Bootstrap ──
_HERE = Path(__file__).resolve().parent
_PROJ_PKG = _HERE.parent
_PROJECTS = _PROJ_PKG.parent
_FLASH_ROOT = _PROJECTS.parent
_PARENT = _FLASH_ROOT.parent
# flash 根目录在 sys.path 中即可 `import flash.*` 与 `import output_processors.*`
for _p in (_FLASH_ROOT, _PARENT):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

# ── PPT-friendly plot style (fonts >= 18, English only) ──
from output_processors.plotter.plot_style import (  # noqa: E402
    apply_plot_style,
    english,
    save_figure,
    PPT_FIGSIZE_WIDE,
)

DEFAULT_RUNS_DIR = _HERE / "runs_ch_center_compare"
DEFAULT_OUT_DIR = _HERE / "compare_plots"


def _load_result(h5_path: Path):
    import h5py
    with h5py.File(str(h5_path), "r") as f:
        t = f["t"][:]
        x = f["x"][:]
        data = {k: f[k][:] for k in f.keys() if k not in ("t", "x")}
    return t, x, data


def plot_compare(runs_dir=None, out_dir=None):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    apply_plot_style()   # global: fonts >= 18, English, dpi=200

    runs_dir = Path(runs_dir or DEFAULT_RUNS_DIR)
    out_dir = Path(out_dir or DEFAULT_OUT_DIR)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Read comparison summary
    summary_path = runs_dir / "compare_summary.json"
    if not summary_path.exists():
        print(f"Comparison summary not found: {summary_path}")
        print("Please run: python run_compare.py first")
        sys.exit(1)
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    densities = summary["densities"]

    # Load both result sets
    datasets = []
    for i, dens in enumerate(densities):
        res = summary["results"][i]
        t, x, data = _load_result(Path(res["result_h5"]))
        datasets.append({"dens": dens, "t": t, "x": x, "data": data})
        print(f"  [dens={dens:g}] t: {len(t)} pts, x: {len(x)} pts, "
              f"fields: {list(data.keys())[:6]}")

    # ── Figure 1: final-time dens(x) profile comparison ──
    fig, ax = plt.subplots(figsize=PPT_FIGSIZE_WIDE)
    for ds in datasets:
        data = ds["data"]
        if "dens" not in data:
            print("  Warning: no dens field, skip profile plot")
            continue
        dens_field = data["dens"]  # (Nt, Nx)
        ax.plot(ds["x"] * 1e4, dens_field[-1], lw=2.5,
                label=english(
                    f"rho_CH={ds['dens']:g} g/cm^3 (t={ds['t'][-1]*1e12:.0f} ps)"))
    ax.set_xlabel(english("x (um)"))
    ax.set_ylabel(english("density (g/cm^3)"))
    ax.set_title(english("ch_center Density Comparison - "
                         "Spatial Profile (Final Time)"))
    ax.legend()
    ax.grid(alpha=0.3)
    p1 = out_dir / "compare_dens_profile.png"
    fig.tight_layout()
    save_figure(fig, str(p1))
    print(f"  OK {p1}")

    # ── Figure 2: central dens(t) time evolution comparison ──
    fig, ax = plt.subplots(figsize=PPT_FIGSIZE_WIDE)
    for ds in datasets:
        data = ds["data"]
        if "dens" not in data:
            continue
        dens_field = data["dens"]
        # central point: x closest to 0
        idx_center = int(np.argmin(np.abs(ds["x"])))
        ax.plot(ds["t"] * 1e12, dens_field[:, idx_center], lw=2.5,
                label=english(f"rho_CH={ds['dens']:g} g/cm^3"))
    ax.set_xlabel(english("time (ps)"))
    ax.set_ylabel(english("central density (g/cm^3)"))
    ax.set_title(english("ch_center Density Comparison - "
                         "Central Density vs Time"))
    ax.legend()
    ax.grid(alpha=0.3)
    p2 = out_dir / "compare_dens_time.png"
    fig.tight_layout()
    save_figure(fig, str(p2))
    print(f"  OK {p2}")

    # ── Figure 3: side-by-side x-t density heatmaps ──
    n = len(datasets)
    fig, axes = plt.subplots(1, n, figsize=(8 * n, 6), sharey=True)
    if n == 1:
        axes = [axes]
    for ax, ds in zip(axes, datasets):
        data = ds["data"]
        if "dens" not in data:
            continue
        X, T = np.meshgrid(ds["x"] * 1e4, ds["t"] * 1e12)
        im = ax.pcolormesh(T, X, data["dens"], shading="auto", cmap="viridis")
        ax.set_xlabel(english("time (ps)"))
        ax.set_title(english(f"rho_CH={ds['dens']:g} g/cm^3"))
        cbar = fig.colorbar(im, ax=ax)
        cbar.set_label(english("density (g/cm^3)"))
    axes[0].set_ylabel(english("x (um)"))
    fig.suptitle(english("ch_center Density Comparison - x-t Heatmap"),
                 fontsize=22, weight="bold")
    p3 = out_dir / "compare_dens_heatmap.png"
    fig.tight_layout()
    save_figure(fig, str(p3))
    print(f"  OK {p3}")

    print(f"\nComparison plots saved to: {out_dir}")
    return out_dir


def main():
    parser = argparse.ArgumentParser(description="ch_center dual-density "
                                                 "comparison plotting")
    parser.add_argument("--runs-dir", default=None,
                        help="Run directory (default: runs_ch_center_compare)")
    parser.add_argument("--out", default=None,
                        help="Output directory (default: compare_plots)")
    args = parser.parse_args()
    plot_compare(runs_dir=args.runs_dir, out_dir=args.out)


if __name__ == "__main__":
    main()
