"""grad_dens_sandwich sim_input 文件源 (嵌入内容, 由 build 脚本从原场景精确提取)

非 py 输入文件的唯一事实来源; gen_flash_inputs.py 读取本模块写出 sim_input/。
文本内容统一 LF 存储; 写出时 run_flash.bat 恢复 CRLF, 其余保持 LF。
"""

# cn4 表来源: 包内中央表库 (相对 eos_op_data 根)
CN4_TABLE_SOURCES = {
    "Z14_1.00-20260708_0850.cn4": "Gen_eos_op_data/Z14_1.00-20260708_0850/Z14_1.00-20260708_0850.cn4",
    "Z06_0.50-Z01_0.50-20260708_0850.cn4": "Gen_eos_op_data/Z06_0.50-Z01_0.50-20260708_0850/Z06_0.50-Z01_0.50-20260708_0850.cn4",
    "Z02_1.00-20260708_0851.cn4": "Gen_eos_op_data/Z02_1.00-20260708_0851/Z02_1.00-20260708_0851.cn4",
}


SIM_INPUT_FILES = {
    'Config': r'''# Configuration file for GradDensSandwich simulation
# HE-CH-Si-CH-HE symmetric structure with gradient CH density
# Based on the standard LaserSlab configuration
# Generated by ConfigGenerator (self-contained)
REQUIRES Driver
REQUIRES physics/Hydro

USESETUPVARS ThreeT

IF ThreeT
   REQUESTS physics/Diffuse/DiffuseMain/Unsplit

   REQUESTS physics/sourceTerms/Heatexchange/HeatexchangeMain/Spitzer
   REQUESTS physics/materialProperties/Conductivity/ConductivityMain/SpitzerHighZ
ENDIF

# Setup example:
# ./setup -auto QC/grad_dens_sandwich -1d +cartesian -nxb=16 \
#         -maxblocks=2048 +hdf5typeio species=cham,targ,poly \
#         +mtmmmt +laser +uhd3t +mgd mgd_meshgroups=10 \
#         -objdir=QC/object_grad_dens_sandwich

DATAFILES Z14_1.00-20260708_0850.cn4
DATAFILES Z02_1.00-20260708_0851.cn4

##########################
#                        #
#   RUNTIME PARAMETERS   #
#                        #
##########################

D sim_initGeom Use a spherical target if sphere, default to slab
PARAMETER sim_initGeom STRING "slab" ["slab","sphere"]

D sim_targetRadius The radius to use for the target
PARAMETER sim_targetRadius REAL 0.0050

D sim_targHeight The height of the target off y-axis
PARAMETER sim_targHeight REAL 0.0250

D sim_vacuumHeight The thickness of the vacuum region in front of the target
PARAMETER sim_vacuumHeight REAL 0.0200

# Target material defaults:
D sim_rhoTarg Initial target density
PARAMETER sim_rhoTarg   REAL 2.7

D sim_teleTarg Initial target electron temperature
PARAMETER sim_teleTarg  REAL 290.11375

D sim_tionTarg Initial target ion temperature
PARAMETER sim_tionTarg  REAL 290.11375

D sim_tradTarg Initial target radiation temperature
PARAMETER sim_tradTarg  REAL 290.11375

D sim_zminTarg target minimum zbar allowed
PARAMETER sim_zminTarg  REAL 0.0

D sim_eosTarg chamber EOS type
PARAMETER sim_eosTarg   STRING "eos_tab" ["eos_tab","eos_gam"]

# Chamber material defaults:
D sim_rhoCham Initial chamber density
PARAMETER sim_rhoCham   REAL 2.655e-07

D sim_teleCham Initial chamber electron temperature
PARAMETER sim_teleCham  REAL 290.11375

D sim_tionCham Initial chamber ion temperature
PARAMETER sim_tionCham  REAL 290.11375

D sim_tradCham Initial chamber radiation temperature
PARAMETER sim_tradCham  REAL 290.11375

D sim_eosCham chamber EOS type
PARAMETER sim_eosCham   STRING "eos_gam" ["eos_tab","eos_gam"]

D lase_variable saves (density of) the irradiated energy from EnergyDeposition unit, cf. RP ed_irradVarName
VARIABLE lase TYPE: PER_VOLUME

DATAFILES Z06_0.50-Z01_0.50-20260708_0850.cn4
# Poly (CH) material:
D sim_polyHeight CH layer half-thickness (computed from max ch_posx)
PARAMETER sim_polyHeight REAL 0.01
D sim_rhoPoly Initial CH density (fallback when gradient disabled)
PARAMETER sim_rhoPoly REAL 1.05
D ch_num Number of active CH density gradient control point pairs (0=none)
PARAMETER ch_num INTEGER 0
D ch_posx_1 CH density gradient control point 1 position (cm)
PARAMETER ch_posx_1 REAL 0.0
D ch_dens_1 CH density gradient control point 1 density (g/cm^3)
PARAMETER ch_dens_1 REAL 0.0
D ch_posx_2 CH density gradient control point 2 position (cm)
PARAMETER ch_posx_2 REAL 0.0
D ch_dens_2 CH density gradient control point 2 density (g/cm^3)
PARAMETER ch_dens_2 REAL 0.0
D ch_posx_3 CH density gradient control point 3 position (cm)
PARAMETER ch_posx_3 REAL 0.0
D ch_dens_3 CH density gradient control point 3 density (g/cm^3)
PARAMETER ch_dens_3 REAL 0.0
D ch_posx_4 CH density gradient control point 4 position (cm)
PARAMETER ch_posx_4 REAL 0.0
D ch_dens_4 CH density gradient control point 4 density (g/cm^3)
PARAMETER ch_dens_4 REAL 0.0
D ch_posx_5 CH density gradient control point 5 position (cm)
PARAMETER ch_posx_5 REAL 0.0
D ch_dens_5 CH density gradient control point 5 density (g/cm^3)
PARAMETER ch_dens_5 REAL 0.0
D ch_posx_6 CH density gradient control point 6 position (cm)
PARAMETER ch_posx_6 REAL 0.0
D ch_dens_6 CH density gradient control point 6 density (g/cm^3)
PARAMETER ch_dens_6 REAL 0.0
D ch_posx_7 CH density gradient control point 7 position (cm)
PARAMETER ch_posx_7 REAL 0.0
D ch_dens_7 CH density gradient control point 7 density (g/cm^3)
PARAMETER ch_dens_7 REAL 0.0
D ch_posx_8 CH density gradient control point 8 position (cm)
PARAMETER ch_posx_8 REAL 0.0
D ch_dens_8 CH density gradient control point 8 density (g/cm^3)
PARAMETER ch_dens_8 REAL 0.0
D ch_posx_9 CH density gradient control point 9 position (cm)
PARAMETER ch_posx_9 REAL 0.0
D ch_dens_9 CH density gradient control point 9 density (g/cm^3)
PARAMETER ch_dens_9 REAL 0.0
D ch_posx_10 CH density gradient control point 10 position (cm). 0=unused
PARAMETER ch_posx_10 REAL 0.0
D ch_dens_10 CH density gradient control point 10 density (g/cm^3)
PARAMETER ch_dens_10 REAL 0.0
D sim_telePoly Initial CH electron temperature
PARAMETER sim_telePoly REAL 290.11375
D sim_tionPoly Initial CH ion temperature
PARAMETER sim_tionPoly REAL 290.11375
D sim_tradPoly Initial CH radiation temperature
PARAMETER sim_tradPoly REAL 290.11375
D ms_polyA CH atomic mass
PARAMETER ms_polyA REAL 6.5
D ms_polyZ CH atomic number
PARAMETER ms_polyZ REAL 3.5
D eos_polyEosType Poly EOS type
PARAMETER eos_polyEosType STRING "eos_tab" ["eos_tab","eos_gam"]
D eos_polySubType Poly EOS subtype
PARAMETER eos_polySubType STRING "ionmix4" ["ionmix4"]
D eos_polyTableFile Poly EOS table
PARAMETER eos_polyTableFile STRING "Z06_0.50-Z01_0.50-20260708_0850.cn4"
D op_polyAbsorb Poly absorption opacity
PARAMETER op_polyAbsorb STRING "op_tabpa"
D op_polyEmiss Poly emission opacity
PARAMETER op_polyEmiss STRING "op_tabpe"
D op_polyTrans Poly transport opacity
PARAMETER op_polyTrans STRING "op_tabro"
D op_polyFileType Poly opacity file type
PARAMETER op_polyFileType STRING "ionmix4"
''',
    'Grid_markRefineDerefine.F90': r'''!!****if* source/Simulation/SimulationMain/LaserSlab_Custom/Grid_markRefineDerefine
!!
!! NAME
!!  Grid_markRefineDerefine
!!
!! SYNOPSIS
!!  call Grid_markRefineDerefine()
!!  
!! DESCRIPTION 
!!  ═══════════════════════════════════════════════════════════════════
!!  模式 C（默认二阶梯度 + 逐块几何区域加密）
!!  ═══════════════════════════════════════════════════════════════════
!!
!!  仿真场景 — 1D 笛卡尔坐标，激光烧蚀多层靶:
!!  ───────────────────────────────────────────────────────────────────
!!  域范围:     x ∈ [sim_xMin, sim_xMax] = [-200, 200] um
!!  
!!  材料布局（对称）:
!!    位置 |x| (um)       材料         目标细化
!!    ─────────────────────────────────────────────
!!    ≤ 0.2             Al 靶材      高精度 (6~8 级)
!!    (0.2, 4]          CH 泡沫      中精度 (1~4 级)
!!    > 4               He 填充      不强制（低精度）
!!
!!  激光条件:
!!    两束 1ns 梯形波（30ps 上升/下降沿, 近似方波）
!!    最大功率密度 5e11 W/cm², 波长 0.351 um
!!    左右两边同时以相同波形入射
!!
!!  细化策略（三层保障）:
!!    ① 二阶梯度加密     — 标准 FLASH 机制，捕获物理量梯度变化
!!    ② 几何区域约束     — 本文件核心，双向约束（refine+derefine）
!!                        ★ 使用边界框重叠（非块中心）判断区域归属
!!                        ★ 解决目标区域 < 最小块尺寸时的失效问题
!!    ③ PARAMESH 邻接限制 — |Δlref| ≤ 1，自然产生平滑空间过渡
!!
!!  目标细化层级（由 lrefine_max 自适应）:
!!    Al 区: lref ∈ [lrefine_max-2, lrefine_max]  (例 lref=8 → [6,8])
!!    CH 区: lref ≤ lrefine_max / 2               (例 lref=8 → ≤4)
!!    He 区: lref ≤ lrefine_min                   (例 lref=1 → ≤1)
!!
!!  分辨率注释（供 .par 文件参考）:
!!  ──────────────────────────────────────────────────────────────
!!  1D: res_min = |xmax - xmin| / (NXB * nblockx * 2^(lrefine_max-1))
!!       res_max = |xmax - xmin| / (NXB * nblockx * 2^(lrefine_min-1))
!!
!!  代入值 xmax=200, xmin=-200, NXB=8 (由 Flash.h 定义), nblockx=1:
!!    lrefine_max=12 → res_min = 400/(8×1×2¹¹) = 400/16384 ≈ 0.0244 um  ✓ (< 0.03 um)
!!    lrefine_max=11 → res_min = 400/(8×1×2¹⁰) = 400/8192  ≈ 0.0488 um  ✗ (> 0.03 um)
!!    lrefine_max=10 → res_min = 400/(8×1×2⁹)  = 400/4096  ≈ 0.0977 um  ✗
!!    lrefine_max=8  → res_min = 400/(8×1×2⁷)  = 400/1024  ≈ 0.391  um  ✗
!!    ────────────────────────────────────────────────────────────────────
!!    lrefine_min=4  → res_max = 400/(8×1×2³)  = 400/64    ≈ 6.25   um
!!    lrefine_min=3  → res_max = 400/(8×1×2²)  = 400/32    ≈ 12.5   um
!!  ──────────────────────────────────────────────────────────────
!!
!!  结论: 满足 Al 分辨率 < 0.03 um 的最小 lrefine_max = 12
!!        推荐: lrefine_max=12, lrefine_min=4, nblockx=1
!!
!! ARGUMENTS
!!  none
!!
!! NOTES
!!  依赖的 Simulation_data 变量:
!!    sim_xMin, sim_xMax       — 计算域边界 (um)
!!    sim_polyHeight           — CH 泡沫层半高 (um)
!!    sim_targHeight           — Al 靶材层半高 (um)
!!
!!  ★ 关键设计说明（2026-07-02）★
!!  区域判断使用边界框重叠（bounding box overlap）而非块中心坐标。
!!  原设计（块中心法）在目标区域宽度 < 最小块尺寸时完全失效：
!!    - Al 区 0.2µm 远小于 lref=1 的块尺寸 50µm
!!    - 没有任何块的中心落在 Al 或 CH 范围内
!!    - 所有块都被归为 He → lref ≤ 1 → 永远达不到高分辨率
!!  新方法检查块的 [LOW, HIGH] 区间是否与目标区域重叠，
!!  即使块远大于目标区域，只要覆盖即触发约束。
!!
!!  参考文件: Grid_markRefineDerefine (11).F90 (AnomalousRefine)
!!            — 模式 C 的完整实现模板
!!
!!***

subroutine Grid_markRefineDerefine()

  ! ─────────────────────────────────────────────────────────────────
  ! ① USE 语句 — 导入 FLASH 模块和仿真参数
  ! ─────────────────────────────────────────────────────────────────

  use Driver_interface, ONLY : Driver_getSimTime
  use Grid_data, ONLY : gr_refine_cutoff, gr_derefine_cutoff, &
                        gr_refine_filter, &
                        gr_numRefineVars, gr_refine_var, &
                        gr_refineOnParticleCount, &
                        gr_enforceMaxRefinement, gr_maxRefine, &
                        gr_lrefineMaxByTime, &
                        gr_lrefineMaxRedDoByTime, &
                        gr_lrefineMaxRedDoByLogR, &
                        gr_lrefineCenterI, gr_lrefineCenterJ, gr_lrefineCenterK, &
                        gr_eosModeNow
  use tree, ONLY : newchild, refine, derefine, stay, nodetype, &
                   lrefine, lrefine_max, lrefine_min, lnblocks
  use Logfile_interface, ONLY : Logfile_stampVarMask
  use Grid_interface, ONLY : Grid_fillGuardCells, &
                             Grid_getListOfBlocks, &
                             Grid_getBlkBoundBox
  use Particles_interface, ONLY : Particles_sinkMarkRefineDerefine
  use Simulation_data, ONLY : &
                              sim_polyHeight, sim_targHeight

  implicit none

#include "constants.h"
#include "Flash.h"

  ! ─────────────────────────────────────────────────────────────────
  ! ② 变量声明
  ! ─────────────────────────────────────────────────────────────────

  ! — 二阶梯度加密相关 —
  real    :: ref_cut, deref_cut, ref_filter
  integer :: l, i, iref

  ! — gcMask 相关 —
  logical, save :: gcMaskArgsLogged = .FALSE.
  integer, save :: eosModeLast = 0
  logical :: doEos = .true.
  integer, parameter :: maskSize = NUNK_VARS + NDIM * NFACE_VARS
  logical, dimension(maskSize) :: gcMask

  ! — 时间相关 —
  real :: time

  ! — 逐块几何加密相关 —
  integer :: blockCount
  integer, dimension(MAXBLOCKS) :: blkList
  integer :: lb
  real, dimension(LOW:HIGH, MDIM) :: boundBox
  integer :: al_target_lref, al_lower_lref, ch_max_lref, he_max_lref

  ! ─────────────────────────────────────────────────────────────────
  ! ③ 模式 A：标准二阶梯度加密流程
  ! ─────────────────────────────────────────────────────────────────

  ! ─── ③-a：时间退粗 ───
  if (gr_lrefineMaxRedDoByTime) then
     call gr_markDerefineByTime()
  end if

  ! ─── ③-b：按时间动态调整最大精度 ───
  if (gr_lrefineMaxByTime) then
     call gr_setMaxRefineByTime()
  end if

  ! ─── ③-c：EoS 模式变更检测 ───
  ! 如果 EoS 模式从上个时间步发生了变化，重置 gcMaskArgsLogged 标志
  ! 这样下一次 Grid_fillGuardCells 会重新记录掩码日志
  if (gr_eosModeNow .NE. eosModeLast) then
     gcMaskArgsLogged = .FALSE.
     eosModeLast = gr_eosModeNow
  end if

  ! ─── ③-d：构建 gcMask ───
  ! gcMask 指定 Grid_fillGuardCells 需要填充哪些变量的 GuardCell
  ! 只包含加密判断需要的变量（性能考虑）
  gcMask = .false.
  do i = 1, gr_numRefineVars
     iref = gr_refine_var(i)
     if (iref > 0) gcMask(iref) = .TRUE.
  end do
  ! 同时填充面变量的 GuardCell（如果有）
  gcMask(NUNK_VARS+1:min(maskSize, NUNK_VARS+NDIM*NFACE_VARS)) = .TRUE.

  ! ─── ③-e：记录 gcMask 日志（仅首次或 EoS 变更后）───
  if (.NOT. gcMaskArgsLogged) then
     call Logfile_stampVarMask(gcMask, .true., &
          '[Grid_markRefineDerefine]', 'gcArgs')
  end if

  ! ─── ③-f：填充 GuardCell ───
  ! CENTER_FACES：同时填充 CENTER 和 FACE 变量的 GuardCell
  ! doEos=.true.：填充后自动调用 EoS，保持热力学一致性
  call Grid_fillGuardCells(CENTER_FACES, ALLDIR, doEos=.true., &
       maskSize=maskSize, mask=gcMask, makeMaskConsistent=.true., &
       doLogMask=.NOT.gcMaskArgsLogged, selectBlockType=ACTIVE_BLKS)
  gcMaskArgsLogged = .TRUE.

  ! ─── ③-g：重置 refine/derefine/stay 标志 ───
  ! 重要：所有标志必须每个时间步重置，因为它们是 SAVE 属性数组
  newchild(:) = .FALSE.
  refine(:)   = .FALSE.
  derefine(:) = .FALSE.
  stay(:)     = .FALSE.

  ! ─── ③-h：标准二阶梯度加密循环 ───
  ! 对每个加密变量计算二阶梯度误差，与阈值比较
  ! 误差 > refine_cutoff   → 标记 refine
  ! 误差 < derefine_cutoff → 标记 derefine
  do l = 1, gr_numRefineVars
     iref     = gr_refine_var(l)
     ref_cut  = gr_refine_cutoff(l)
     deref_cut  = gr_derefine_cutoff(l)
     ref_filter = gr_refine_filter(l)
     call gr_markRefineDerefine(iref, ref_cut, deref_cut, ref_filter)
  end do

  ! ─────────────────────────────────────────────────────────────────
  ! ④ 模式 C 附加：逐块几何区域约束（边界框重叠版）
  ! ─────────────────────────────────────────────────────────────────
  !
  !  原理：使用块的边界框（bounding box）与材料区域的交集来判断。
  !        原代码用块中心坐标判断，当材料区域宽度小于最小块尺寸时，
  !        没有块的中心落在目标区域内，导致约束完全失效。
  !        例如 Al 区 0.2µm 远小于最小块 50µm → 约束永远不触发
  !
  !  方法：检查块的 [LOW, HIGH] 区间是否与材料区域重叠：
  !    - 块与 Al 区重叠 → Al 约束（必须加密到高精度）
  !    - 块与 CH 重叠但不与 Al 重叠 → CH 约束
  !    - 其他 → He 约束（退粗）
  !
  !  目标细化层级（由 lrefine_max 自适应，不硬编码）:
  !    Al 区: 下限 = lrefine_max-2, 上限 = lrefine_max
  !           确保亚微米 Al 层有足够分辨率
  !    CH 区: 上限 = lrefine_max/2（≤4 in typical case）
  !           避免密度界面梯度引起非物理过度细化
  !    He 区: 上限 = lrefine_min（自然退粗到最粗网格）
  !
  !  过渡机制：PARAMESH 要求相邻块的细化层级差 |Δlref| ≤ 1。
  !           即使 CH 区 derefine 标记为 4，Al 边界附近的块
  !           会被 PARAMESH 维持在高一级（被动产生平滑过渡带）。
  ! ─────────────────────────────────────────────────────────────────

  ! —— ④-a：计算各材料区域的层级约束 ——
  ! Al 区：下限 = lrefine_max-2, 上限 = lrefine_max
  al_target_lref = lrefine_max
  al_lower_lref  = max(lrefine_min, lrefine_max - 2)
  ! CH 区：上限 = lrefine_max/2（不低于 2）
  ch_max_lref = max(lrefine_min, lrefine_max / 2)
  if (ch_max_lref < 2) ch_max_lref = 2
  ! He 区：上限 = lrefine_min（退粗到最粗）
  he_max_lref = lrefine_min

  ! —— ④-b：获取所有活动块列表 ——
  call Grid_getListOfBlocks(ACTIVE_BLKS, blkList, blockCount)

  ! —— ④-c：逐块判断并标记 ——
  do i = 1, blockCount
     lb = blkList(i)

     ! 只处理叶块（非叶块在末尾统一清理）
     if (nodetype(lb) /= LEAF) cycle

     ! 获取块的包围盒
     call Grid_getBlkBoundBox(lb, boundBox)

     ! ★━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━★★
     !  ★ 关键修改：用边界框重叠替代块中心判断 ★
     !  ★ 当目标区域 < 块尺寸时，块中心法失效    ★
     ! ★━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━★
     !
     ! 判断块是否与 Al 靶材区重叠:
     !   Al 区范围: x ∈ [-sim_targHeight, sim_targHeight]
     !   如果块边界与 Al 区间有交集 → Al 约束
     if (boundBox(HIGH, IAXIS) >= -sim_targHeight .and. &
         boundBox(LOW, IAXIS)  <=  sim_targHeight) then

        ! ═══ Al 靶材区 ═══
        !  约束: lref ∈ [lrefine_max-2, lrefine_max]
        if (lrefine(lb) < al_lower_lref) then
           ! 精度不足 → 强制 refine
           refine(lb)   = .true.
           derefine(lb) = .false.
        else if (lrefine(lb) > al_target_lref) then
           ! 超出上限（罕见，安全网）→ 强制 derefine
           refine(lb)   = .false.
           derefine(lb) = .true.
        end if
        ! lref 在范围内 → 保留梯度加密结果

     ! 判断块是否与 CH 泡沫区重叠（且不与 Al 重叠）:
     !   CH 区范围: x ∈ [-sim_polyHeight, sim_polyHeight]
     !   注: 上面已排除 Al 重叠，此处只需检查 CH 重叠即可
     else if (boundBox(HIGH, IAXIS) >= -sim_polyHeight .and. &
              boundBox(LOW, IAXIS)  <=  sim_polyHeight) then

        ! ═══ CH 泡沫区 ═══
        !  约束: lref ≤ lrefine_max/2
        !  应用: 双向 — 不足时 refine, 过度时 derefine
        if (lrefine(lb) < ch_max_lref) then
           ! 精度不足（靠近 Al 边界可能被退粗）→ 确保最低精度
           refine(lb)   = .true.
           derefine(lb) = .false.
        else if (lrefine(lb) > ch_max_lref) then
           ! ❗ 过度细化（梯度在 CH/He 边界误判）→ 强制退粗
           refine(lb)   = .false.
           derefine(lb) = .true.
        end if

     else
        ! ═══ He 填充区 ═══
        !  约束: lref ≤ lrefine_min
        !  只有 derefine 方向，不主动 refine
        if (lrefine(lb) > he_max_lref) then
           refine(lb)   = .false.
           derefine(lb) = .true.
        end if
     end if
  end do

  ! ─────────────────────────────────────────────────────────────────
  ! ⑤ 标准后处理收尾
  ! ─────────────────────────────────────────────────────────────────

  ! —— ⑤-a：PARAMESH2 兼容 ——
#ifdef FLASH_GRID_PARAMESH2
  if (gr_numRefineVars .LE. 0) then
     call gr_markRefineDerefine(-1, 0.0, 0.0, 0.0)
  end if
#endif

  ! —— ⑤-b：粒子计数加密 ——
  if (gr_refineOnParticleCount) call gr_ptMarkRefineDerefine()

  ! —— ⑤-c：最大精度强制 ——
  ! 确保任何块的 refine 层级不超过 gr_maxRefine（安全网）
  if (gr_enforceMaxRefinement) call gr_enforceMaxRefine(gr_maxRefine)

  ! —— ⑤-d：对数半径退粗限制（可选） ——
  if (gr_lrefineMaxRedDoByLogR) &
       call gr_unmarkRefineByLogRadius(gr_lrefineCenterI, &
                                       gr_lrefineCenterJ, gr_lrefineCenterK)

  ! —— ⑤-e：Sink 粒子加密 ——
  call Particles_sinkMarkRefineDerefine()

  ! —— ⑤-f：★ 最关键：非叶块标志清理 ★ ——
  ! 只有 nodetype == LEAF 的块才能被 refine 或 derefine
  ! 父块（有子块的块）如果被标记了 refine，PARAMESH 会崩溃
  where (nodetype(:) .NE. LEAF)
     refine(:)   = .false.
     derefine(:) = .false.
  end where

  return
end subroutine Grid_markRefineDerefine
''',
    'Makefile': r'''Simulation += Simulation_data.o
''',
    'Simulation_data.F90': r'''!!****if* source/Simulation/SimulationMain/LaserSlab/Simulation_data
!!
!! NAME
!!  Simulation_data
!!
!! SYNOPSIS
!!  Use Simulation_data
!!
!! DESCRIPTION
!!
!!  Store the simulation data for GradDensSandwich simulation
!!  (3-species: cham=He, targ=Si, poly=CH)
!!
!!  Extended runtime parameters for CH density gradient control:
!!    ch_posx_1..10, ch_dens_1..10  — CH density control points
!!    sim_polyHeight is computed from the maximum active ch_posx
!!    (not set directly in .par file)
!!
!!***
module Simulation_data

  implicit none

#include "constants.h"

  !! *** Runtime Parameters *** !!

  ! Geometry
  real, save :: sim_targHeight
  real, save :: sim_polyHeight      ! Computed from max active ch_posx

  ! Si (target) material
  real,    save :: sim_rhoTarg
  real,    save :: sim_teleTarg
  real,    save :: sim_tionTarg
  real,    save :: sim_tradTarg

  ! CH (poly) material — base params
  real,    save :: sim_rhoPoly      ! Fallback CH density (when gradient disabled)
  real,    save :: sim_telePoly
  real,    save :: sim_tionPoly
  real,    save :: sim_tradPoly

  ! CH density gradient: ch_num controls how many pairs are active (CGS)
  integer, save :: ch_num           ! Number of active pairs (0 = no gradient)
  real,    save :: ch_posx_1,  ch_dens_1
  real,    save :: ch_posx_2,  ch_dens_2
  real,    save :: ch_posx_3,  ch_dens_3
  real,    save :: ch_posx_4,  ch_dens_4
  real,    save :: ch_posx_5,  ch_dens_5
  real,    save :: ch_posx_6,  ch_dens_6
  real,    save :: ch_posx_7,  ch_dens_7
  real,    save :: ch_posx_8,  ch_dens_8
  real,    save :: ch_posx_9,  ch_dens_9
  real,    save :: ch_posx_10, ch_dens_10

  ! He (chamber) material
  real,    save :: sim_rhoCham
  real,    save :: sim_teleCham
  real,    save :: sim_tionCham
  real,    save :: sim_tradCham

  logical, save :: sim_killdivb = .FALSE.
  real, save :: sim_smallX
  character(len=MAX_STRING_LENGTH), save :: sim_initGeom

end module Simulation_data
''',
    'Simulation_init.F90': r'''!!****if* source/Simulation/SimulationMain/LaserSlab/Simulation_init
!!
!! NAME
!!  Simulation_init
!!
!! SYNOPSIS
!!  Simulation_init()
!!
!! DESCRIPTION
!!
!!  Initializes all runtime parameters for GradDensSandwich simulation
!!
!!***
subroutine Simulation_init()
  use Simulation_data
  use RuntimeParameters_interface, ONLY : RuntimeParameters_get
  use Logfile_interface, ONLY : Logfile_stamp

  implicit none

#include "constants.h"
#include "Flash.h"

  ! Geometry
  call RuntimeParameters_get('sim_targHeight', sim_targHeight)
  call RuntimeParameters_get('sim_polyHeight', sim_polyHeight)

  ! Si (target)
  call RuntimeParameters_get('sim_rhoTarg', sim_rhoTarg)
  call RuntimeParameters_get('sim_teleTarg', sim_teleTarg)
  call RuntimeParameters_get('sim_tionTarg', sim_tionTarg)
  call RuntimeParameters_get('sim_tradTarg', sim_tradTarg)

  ! CH (poly)
  call RuntimeParameters_get('sim_rhoPoly', sim_rhoPoly)
  call RuntimeParameters_get('sim_telePoly', sim_telePoly)
  call RuntimeParameters_get('sim_tionPoly', sim_tionPoly)
  call RuntimeParameters_get('sim_tradPoly', sim_tradPoly)

  ! CH density gradient: number of active pairs
  call RuntimeParameters_get('ch_num', ch_num)

  ! CH density gradient control points (up to 10 pairs)
  call RuntimeParameters_get('ch_posx_1',  ch_posx_1)
  call RuntimeParameters_get('ch_dens_1',  ch_dens_1)
  call RuntimeParameters_get('ch_posx_2',  ch_posx_2)
  call RuntimeParameters_get('ch_dens_2',  ch_dens_2)
  call RuntimeParameters_get('ch_posx_3',  ch_posx_3)
  call RuntimeParameters_get('ch_dens_3',  ch_dens_3)
  call RuntimeParameters_get('ch_posx_4',  ch_posx_4)
  call RuntimeParameters_get('ch_dens_4',  ch_dens_4)
  call RuntimeParameters_get('ch_posx_5',  ch_posx_5)
  call RuntimeParameters_get('ch_dens_5',  ch_dens_5)
  call RuntimeParameters_get('ch_posx_6',  ch_posx_6)
  call RuntimeParameters_get('ch_dens_6',  ch_dens_6)
  call RuntimeParameters_get('ch_posx_7',  ch_posx_7)
  call RuntimeParameters_get('ch_dens_7',  ch_dens_7)
  call RuntimeParameters_get('ch_posx_8',  ch_posx_8)
  call RuntimeParameters_get('ch_dens_8',  ch_dens_8)
  call RuntimeParameters_get('ch_posx_9',  ch_posx_9)
  call RuntimeParameters_get('ch_dens_9',  ch_dens_9)
  call RuntimeParameters_get('ch_posx_10', ch_posx_10)
  call RuntimeParameters_get('ch_dens_10', ch_dens_10)

  ! He (chamber)
  call RuntimeParameters_get('sim_rhoCham', sim_rhoCham)
  call RuntimeParameters_get('sim_teleCham', sim_teleCham)
  call RuntimeParameters_get('sim_tionCham', sim_tionCham)
  call RuntimeParameters_get('sim_tradCham', sim_tradCham)

  call RuntimeParameters_get('smallX', sim_smallX)
  call RuntimeParameters_get('sim_initGeom', sim_initGeom)

end subroutine Simulation_init
''',
    'Simulation_initBlock.F90': r'''!!****if* source/Simulation/SimulationMain/LaserSlab/Simulation_initBlock
!!
!! NAME
!!  Simulation_initBlock
!!
!! SYNOPSIS
!!  call Simulation_initBlock(integer(IN) :: blockID)
!!
!! DESCRIPTION
!!
!!  Initializes fluid data for a specified block.
!!  GradDensSandwich — HE-CH-Si-CH-HE symmetric 5-layer structure
!!  with gradient CH density controlled by ch_num (active pair count)
!!  and up to 10 (ch_posx, ch_dens) control point pairs:
!!
!!    Layer 1 — He (cham):    |x| > sim_polyHeight
!!    Layer 2 — CH (poly):    sim_targHeight < |x| <= sim_polyHeight
!!       Density interpolated among first ch_num pairs in CH region
!!       ch_num=0 → uniform sim_rhoPoly throughout CH
!!    Layer 3 — Si (targ):    |x| <= sim_targHeight
!!    Layer 4 — CH (poly):    symmetric to layer 2
!!    Layer 5 — He (cham):    symmetric to layer 1
!!
!!  sim_polyHeight = abs(ch_posx(ch_num) - ch_posx(1))
!!  Pairs 1..ch_num must have monotonically increasing ch_posx.
!!
!!***
subroutine Simulation_initBlock(blockId)
  use Simulation_data
  use Grid_interface, ONLY : Grid_getBlkIndexLimits, &
       Grid_getCellCoords, Grid_putPointData, &
       Grid_getBlkPtr, Grid_releaseBlkPtr

  use Driver_interface, ONLY: Driver_abortFlash
  use RadTrans_interface, ONLY: RadTrans_mgdEFromT

  implicit none

#include "constants.h"
#include "Flash.h"

  integer, intent(in) :: blockId

  integer :: i, j, k, n, m
  integer :: blkLimits(2, MDIM)
  integer :: blkLimitsGC(2, MDIM)
  integer :: axis(MDIM)
  real, allocatable :: xcent(:), ycent(:), zcent(:)
  real :: tradActual
  real :: rho, tele, trad, tion
  real :: frac, abs_x
  integer :: species
  real, pointer, dimension(:,:,:,:) :: facexData, faceyData
  logical :: is_transition
#if NDIM > 0
  real, pointer, dimension(:,:,:,:) :: facezData
#endif

  ! Local work arrays for gradient points
  integer, parameter :: MAX_GP = 10
  real :: gp_x(MAX_GP), gp_d(MAX_GP)
  integer :: n_active, idx_lo, idx_hi

#ifndef CHAM_SPEC
  integer :: CHAM_SPEC = 1, TARG_SPEC = 2, POLY_SPEC = 3
#endif

  ! ── Step 1: Collect active gradient points ──
  ! ch_num controls how many pairs are used (0 = no gradient)
  n_active = min(ch_num, MAX_GP)

  if (n_active > 0) then
     ! Copy control point pairs to work array
     do i = 1, n_active
        select case(i)
        case(1);  gp_x(i) = ch_posx_1;  gp_d(i) = ch_dens_1
        case(2);  gp_x(i) = ch_posx_2;  gp_d(i) = ch_dens_2
        case(3);  gp_x(i) = ch_posx_3;  gp_d(i) = ch_dens_3
        case(4);  gp_x(i) = ch_posx_4;  gp_d(i) = ch_dens_4
        case(5);  gp_x(i) = ch_posx_5;  gp_d(i) = ch_dens_5
        case(6);  gp_x(i) = ch_posx_6;  gp_d(i) = ch_dens_6
        case(7);  gp_x(i) = ch_posx_7;  gp_d(i) = ch_dens_7
        case(8);  gp_x(i) = ch_posx_8;  gp_d(i) = ch_dens_8
        case(9);  gp_x(i) = ch_posx_9;  gp_d(i) = ch_dens_9
        case(10); gp_x(i) = ch_posx_10; gp_d(i) = ch_dens_10
        end select
     enddo

     ! ── Step 2: Validate monotonic increasing (no sorting) ──
     do i = 2, n_active
        if (gp_x(i) <= gp_x(i-1)) then
           call Driver_abortFlash( &
                "GridReDe: ch_posx must be monotonically increasing. " // &
                "ch_posx_(i) <= ch_posx_(i-1) at i=")
        endif
     enddo

     ! ── Step 3: Compute sim_polyHeight = abs(end - start) ──
     sim_polyHeight = abs(gp_x(n_active) - gp_x(1))
  endif

  ! get the coordinate information for the current block from the database
  call Grid_getBlkIndexLimits(blockId,blkLimits,blkLimitsGC)

  allocate(xcent(blkLimitsGC(HIGH, IAXIS)))
  call Grid_getCellCoords(IAXIS, blockId, CENTER, .true., &
       xcent, blkLimitsGC(HIGH, IAXIS))
  allocate(ycent(blkLimitsGC(HIGH, JAXIS)))
  call Grid_getCellCoords(JAXIS, blockId, CENTER, .true., &
       ycent, blkLimitsGC(HIGH, JAXIS))
  allocate(zcent(blkLimitsGC(HIGH, KAXIS)))
  call Grid_getCellCoords(KAXIS, blockId, CENTER, .true., &
       zcent, blkLimitsGC(HIGH, KAXIS))

#if NFACE_VARS > 0
  if (sim_killdivb) then
     call Grid_getBlkPtr(blockID,facexData,FACEX)
     call Grid_getBlkPtr(blockID,faceyData,FACEY)
     if (NDIM>2) call Grid_getBlkPtr(blockID,facezData,FACEZ)
  endif
#endif

  ! Loop over cells and set the initial state
  do k = blkLimits(LOW,KAXIS),blkLimits(HIGH,KAXIS)
     do j = blkLimits(LOW,JAXIS),blkLimits(HIGH,JAXIS)
        do i = blkLimits(LOW,IAXIS),blkLimits(HIGH,IAXIS)

           axis(IAXIS) = i
           axis(JAXIS) = j
           axis(KAXIS) = k

           species = CHAM_SPEC
           is_transition = .false.

           if (sim_initGeom == "slab") then
              if (NDIM == 1) then
                 abs_x = abs(xcent(i))
                 if (abs_x <= sim_targHeight) then
                    species = TARG_SPEC
                 else if (abs_x <= sim_polyHeight) then
                    species = POLY_SPEC
                 end if
              end if
           end if

           if (.not. is_transition) then
              if (species == TARG_SPEC) then
                 rho  = sim_rhoTarg
                 tele = sim_teleTarg
                 tion = sim_tionTarg
                 trad = sim_tradTarg
              else if (species == POLY_SPEC) then
                 ! ── CH density from gradient or fallback ──
                 if (n_active >= 2) then
                    abs_x = abs(xcent(i))
                    if (abs_x <= gp_x(1)) then
                       rho = gp_d(1)
                    else if (abs_x >= gp_x(n_active)) then
                       rho = gp_d(n_active)
                    else
                       idx_lo = 1
                       do m = 2, n_active
                          if (abs_x <= gp_x(m)) then
                             idx_lo = m - 1
                             exit
                          endif
                       enddo
                       idx_hi = idx_lo + 1
                       frac = (abs_x - gp_x(idx_lo)) &
                            / (gp_x(idx_hi) - gp_x(idx_lo))
                       rho = gp_d(idx_lo) &
                            + frac * (gp_d(idx_hi) - gp_d(idx_lo))
                    endif
                 else if (n_active == 1) then
                    rho = gp_d(1)
                 else
                    rho = sim_rhoPoly
                 endif
                 tele = sim_telePoly
                 tion = sim_tionPoly
                 trad = sim_tradPoly
              else
                 rho  = sim_rhoCham
                 tele = sim_teleCham
                 tion = sim_tionCham
                 trad = sim_tradCham
              end if
           end if

           call Grid_putPointData(blockId, CENTER, DENS_VAR, EXTERIOR, axis, rho)
           call Grid_putPointData(blockId, CENTER, TEMP_VAR, EXTERIOR, axis, tele)

#ifdef FLASH_3T
           call Grid_putPointData(blockId, CENTER, TION_VAR, EXTERIOR, axis, tion)
           call Grid_putPointData(blockId, CENTER, TELE_VAR, EXTERIOR, axis, tele)

           call RadTrans_mgdEFromT(blockId, axis, trad, tradActual)
           call Grid_putPointData(blockId, CENTER, TRAD_VAR, EXTERIOR, axis, tradActual)
#endif
           if (NSPECIES > 0) then
              do n = SPECIES_BEGIN, SPECIES_END
                 if (n == species) then
                    call Grid_putPointData(blockID, CENTER, n, EXTERIOR, axis, &
                         1.0e0 - (NSPECIES - 1) * sim_smallX)
                 else
                    call Grid_putPointData(blockID, CENTER, n, EXTERIOR, axis, sim_smallX)
                 end if
              enddo
           end if

#ifdef BDRY_VAR
           call Grid_putPointData(blockId, CENTER, BDRY_VAR, EXTERIOR, axis, -1.0)
#endif
         enddo
     enddo
  enddo

#if NFACE_VARS > 0
  if (sim_killdivb) then
     do k = blkLimits(LOW,KAXIS),blkLimits(HIGH,KAXIS)
        do j = blkLimits(LOW,JAXIS),blkLimits(HIGH,JAXIS)
           do i = blkLimits(LOW,IAXIS),blkLimits(HIGH,IAXIS)+1
              facexData(MAG_FACE_VAR,i,j,k)= 0.0
           enddo
        enddo
     enddo
     do k = blkLimits(LOW,KAXIS),blkLimits(HIGH,KAXIS)
        do j = blkLimits(LOW,JAXIS),blkLimits(HIGH,JAXIS)+K2D
           do i = blkLimits(LOW,IAXIS),blkLimits(HIGH,IAXIS)
              faceyData(MAG_FACE_VAR,i,j,k)= 0.0
           enddo
        enddo
     enddo
     if (NDIM>2) then
        do k = blkLimits(LOW,KAXIS),blkLimits(HIGH,KAXIS)+K3D
           do j = blkLimits(LOW,JAXIS),blkLimits(HIGH,JAXIS)
              do i = blkLimits(LOW,IAXIS),blkLimits(HIGH,IAXIS)
                 facezData(MAG_FACE_VAR,i,j,k)= 0.0
              enddo
           enddo
        enddo
     endif
     call Grid_releaseBlkPtr(blockID,facexData,FACEX)
     call Grid_releaseBlkPtr(blockID,faceyData,FACEY)
     if (NDIM>2) call Grid_releaseBlkPtr(blockID,facezData,FACEZ)
  endif
#endif
  deallocate(xcent)
  deallocate(ycent)
  deallocate(zcent)

  return

end subroutine Simulation_initBlock
''',
    'run_flash.sh': r'''#!/bin/bash
# run_flash.sh — GradDensSandwich WSL 自动编译运行脚本
set -e

SIM_NAME="grad_dens_sandwich"
RUN_ID="${2:-000001}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FLASH_HOME="${FLASH_HOME:-$HOME/${FLASH_SIM_USER_DIR:-QC}/FLASH/FLASH4.8}"
SRC_DIR="$FLASH_HOME/source/Simulation/SimulationMain/QC/${SIM_NAME}_${RUN_ID}"
OBJ_DIR="$FLASH_HOME/QC/object_${SIM_NAME}_${RUN_ID}"
RUN_DIR="/tmp/flash_${SIM_NAME}_${RUN_ID}"

echo "=== 清理旧目录 ==="
rm -rf "$SRC_DIR" "$OBJ_DIR"
mkdir -p "$SRC_DIR"

echo "=== 复制源文件 ==="
cp "$SCRIPT_DIR"/*.F90 "$SRC_DIR/"
cp "$SCRIPT_DIR"/Config "$SRC_DIR/"
cp "$SCRIPT_DIR"/Makefile "$SRC_DIR/"
cp "$SCRIPT_DIR"/*.cn4 "$SRC_DIR/"
cp "$SCRIPT_DIR"/*.par "$SRC_DIR/${SIM_NAME}_${RUN_ID}.par"

echo "=== setup ==="
cd "$FLASH_HOME"
./setup -auto "QC/${SIM_NAME}_${RUN_ID}" -1d +cartesian -nxb=16 -maxblocks=2048 +hdf5typeio species=cham,targ,poly +mtmmmt +laser +uhd3t +mgd mgd_meshgroups=10 ed_maxPulseSections=240 -objdir="QC/object_${SIM_NAME}_${RUN_ID}" 2>&1

echo "=== make ==="
cd "$OBJ_DIR"
make -j7 2>&1

echo "=== 运行 ==="
rm -rf "$RUN_DIR"
mkdir -p "$RUN_DIR"
cp "$OBJ_DIR"/flash4 "$RUN_DIR/"
cp "$SRC_DIR"/*.cn4 "$RUN_DIR/"
cp "$SRC_DIR/${SIM_NAME}_${RUN_ID}.par" "$RUN_DIR/flash.par"
touch "$RUN_DIR/lasslab.dat"
cd "$RUN_DIR"
echo "Start: $(date)"
timeout 900 mpirun -np 7 ./flash4 2>&1 || echo "EXIT_CODE=$?"
echo "End: $(date)"
echo "=== HDF5 ==="
ls -lh "$RUN_DIR"/lasslab_hdf5_chk_* 2>/dev/null | wc -l
''',
    'run_flash.bat': r'''@echo off
echo ==== 请在 WSL 环境运行 run_flash.sh ====
echo 当前目录: %CD%
echo 可执行: wsl bash run_flash.sh
pause
''',
    'submit_flash.sh': r'''#!/bin/bash
#SBATCH -J grad_dens_sandwich
#SBATCH -o grad_dens_sandwich_%%j.out
#SBATCH -e grad_dens_sandwich_%%j.err
#SBATCH -N 1
#SBATCH -n 7
#SBATCH --time=01:00:00

set -e
SIM_NAME="grad_dens_sandwich"
RUN_ID="${2:-000001}"
F=$HOME/${FLASH_SIM_USER_DIR:-QC}/FLASH/FLASH4.8
S=$F/source/Simulation/SimulationMain/QC/${SIM_NAME}_${RUN_ID}
O=$F/QC/object_${SIM_NAME}_${RUN_ID}
R=/tmp/flash_${SIM_NAME}_$$

mkdir -p "$S"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
for f in Config Simulation_data.F90 Simulation_init.F90 Simulation_initBlock.F90 Grid_markRefineDerefine.F90 Makefile *.cn4; do
    [ -f "$SCRIPT_DIR/$f" ] && cp "$SCRIPT_DIR/$f" "$S/"
done
cp "$SCRIPT_DIR"/*.par "$S/${SIM_NAME}_${RUN_ID}.par"

cd $F
rm -rf "$O"
./setup -auto "QC/${SIM_NAME}_${RUN_ID}" -1d +cartesian -nxb=16 -maxblocks=2048 +hdf5typeio species=cham,targ,poly +mtmmmt +laser +uhd3t +mgd mgd_meshgroups=10 ed_maxPulseSections=240 -objdir="QC/object_${SIM_NAME}_${RUN_ID}"
cd $O
make -j7

mkdir -p "$R"
cp $O/flash4 "$R/"
cp "$S"/*.cn4 "$R/"
cp "$S/${SIM_NAME}_${RUN_ID}.par" "$R"/flash.par
cd "$R"
mpirun -np 7 ./flash4
echo "=== Output: $R ==="
''',
}
