#!/bin/bash
# FLASH WSL/Linux Run Script (Full Pipeline)
# Generated by ShellScriptGenerator
#
# Performs: setup → compile → copy input → run → collect output

set -e

FLASH_HOME="$HOME/QC/FLASH/FLASH4.8"
PAR_FILE="laserslab_custom.par"
NPROCS=4
OBJ_DIR="QC/LaserSlab_custom"
FLASH_BIN="$FLASH_HOME/$OBJ_DIR/flash4"
SETUP_CMD="./setup -auto QC/LaserSlab_custom -1d +cartesian -nxb=16 +hdf5typeio species=cham,targ +mtmmmt +laser +uhd3t +mgd mgd_meshgroups=10 -objdir=QC/LaserSlab_custom -parfile=laserslab_custom.par"
BUILD_CORES=4
SIM_USER_DIR="QC"
SIM_PATH="QC/LaserSlab_custom"

# Determine script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "=== FLASH Full Pipeline ==="
echo "  FLASH_HOME:   $FLASH_HOME"
echo "  Object dir:   $OBJ_DIR"
echo "  Sim path:     $SIM_PATH"
echo "  Par file:     $PAR_FILE"
echo "  Input dir:    $SCRIPT_DIR"

# ── Step 1: Check FLASH source ──
echo ""
echo "[1/5] Checking FLASH environment..."
if [ ! -d "$FLASH_HOME" ]; then
    echo "ERROR: FLASH_HOME not found: $FLASH_HOME"
    exit 1
fi
echo "  FLASH home found: $FLASH_HOME"

# ── Step 2: Copy source files to SimulationMain ──
echo ""
echo "[2/5] Copying source files to SimulationMain..."
SIM_SRC_DIR="$FLASH_HOME/source/Simulation/SimulationMain/$SIM_PATH"
mkdir -p "$SIM_SRC_DIR"
echo "  Simulation source dir: $SIM_SRC_DIR"
# Copy all FLASH setup source files (Config, Makefile, .F90)
cp "$SCRIPT_DIR"/Config "$SIM_SRC_DIR"/ 2>/dev/null || true
cp "$SCRIPT_DIR"/Makefile "$SIM_SRC_DIR"/ 2>/dev/null || true
cp "$SCRIPT_DIR"/Simulation_*.F90 "$SIM_SRC_DIR"/ 2>/dev/null || true
# Copy data files (.cn4, .par)
cp "$SCRIPT_DIR"/*.cn4 "$SIM_SRC_DIR"/ 2>/dev/null || true
cp "$SCRIPT_DIR/$PAR_FILE" "$SIM_SRC_DIR"/ 2>/dev/null || true
echo "  Source files ready in SimulationMain."

# ── Step 3: Setup + Compile ──
echo ""
echo "[3/5] Setup and compiling FLASH..."
cd "$FLASH_HOME"

if [ -d "$OBJ_DIR" ] && [ -f "$FLASH_BIN" ]; then
    echo "  Object dir exists with binary, skipping setup+make."
else
    echo "  Running setup..."
    eval $SETUP_CMD
    echo "  Setup done. Compiling..."
    cd $OBJ_DIR
    make -j$BUILD_CORES
    echo "  Compilation done."
fi

# ── Step 4: Copy input files to run dir ──
echo ""
echo "[4/6] Copying input files to run directory..."
cd "$FLASH_HOME/$OBJ_DIR"
mkdir -p outputfiles
cp "$SCRIPT_DIR/$PAR_FILE" ./ 2>/dev/null || true
cp "$SCRIPT_DIR"/*.cn4 ./ 2>/dev/null || true
echo "  Input files ready in $FLASH_HOME/$OBJ_DIR."

# ── Step 5: Run FLASH ──
echo ""
echo "[5/6] Running FLASH simulation..."
mpirun -np $NPROCS $FLASH_BIN -par_file $PAR_FILE 2>&1 | tee flash_run.log
FLASH_EXIT=${PIPESTATUS[0]}
echo "  FLASH exit code: $FLASH_EXIT"

# ── Step 6: Collect output ──
echo ""
echo "[6/6] Collecting output files..."
mkdir -p "$SCRIPT_DIR/outputfiles"
cp *.h5 "$SCRIPT_DIR/outputfiles/" 2>/dev/null || true
cp *chk* "$SCRIPT_DIR/outputfiles/" 2>/dev/null || true
cp *plt* "$SCRIPT_DIR/outputfiles/" 2>/dev/null || true
cp flash_run.log "$SCRIPT_DIR/outputfiles/" 2>/dev/null || true

# Summary
echo ""
echo "=== Summary ==="
echo "  Input files:  $SCRIPT_DIR"
echo "  Output files: $SCRIPT_DIR/outputfiles/"
nfiles=$(ls "$SCRIPT_DIR/outputfiles/"*.h5 2>/dev/null | wc -l)
echo "  HDF5 files:   $nfiles"
echo "  FLASH exit:   $FLASH_EXIT"
echo "=== Done ==="

exit $FLASH_EXIT
