"""
FLASH Config 文件生成器 (自包含)
═════════════════════════════════

Config 内容从 LaserSlab/Config 模板提取后硬编码。
"""

from pathlib import Path
from typing import Any, List, Optional, Union


DEFAULT_CONFIG_CONTENT = """\
# Configuration file for hello/LaserSlab1d_new simulation
# Based on the standard LaserSlab configuration
# Generated by ConfigGenerator (self-contained)
REQUIRES Driver
REQUIRES physics/Hydro

USESETUPVARS ThreeT

IF ThreeT
   REQUESTS physics/Diffuse/DiffuseMain/Unsplit

   REQUESTS physics/sourceTerms/Heatexchange/HeatexchangeMain/Spitzer
   REQUESTS physics/materialProperties/Conductivity/ConductivityMain/SpitzerHighZ
ENDIF

# Setup example:
# ./setup -auto <用户名>/LaserSlab1d_new -1d +cartesian -nxb=16 \\
#         -maxblocks=2048 +hdf5typeio species=cham,targ \\
#         +mtmmmt +laser +uhd3t +mgd mgd_meshgroups=10 \\
#         -objdir=<用户名>/object
# 注: <用户名> 通过 flash._core.credentials 设置, 勿硬编码用户名

DATAFILES al-imx-003.cn4
DATAFILES he-imx-005.cn4

##########################
#                        #
#   RUNTIME PARAMETERS   #
#                        #
##########################

D sim_initGeom Use a spherical target if sphere, default to slab
PARAMETER sim_initGeom STRING "slab" ["slab","sphere"]

D sim_targetRadius The radius to use for the target
PARAMETER sim_targetRadius REAL 0.0050

D sim_targetHeight The height of the target off y-axis
PARAMETER sim_targetHeight REAL 0.0250

D sim_vacuumHeight The thickness of the vacuum region in front of the target
PARAMETER sim_vacuumHeight REAL 0.0200

# Target material defaults:
D sim_rhoTarg Initial target density
PARAMETER sim_rhoTarg   REAL 2.7

D sim_teleTarg Initial target electron temperature
PARAMETER sim_teleTarg  REAL 290.11375

D sim_tionTarg Initial target ion temperature
PARAMETER sim_tionTarg  REAL 290.11375

D sim_tradTarg Initial target radiation temperature
PARAMETER sim_tradTarg  REAL 290.11375

D sim_zminTarg target minimum zbar allowed
PARAMETER sim_zminTarg  REAL 0.0

D sim_eosTarg chamber EOS type
PARAMETER sim_eosTarg   STRING "eos_tab" ["eos_tab","eos_gam"]

# Chamber material defaults:
D sim_rhoCham Initial chamber density
PARAMETER sim_rhoCham   REAL 2.655e-07

D sim_teleCham Initial chamber electron temperature
PARAMETER sim_teleCham  REAL 290.11375

D sim_tionCham Initial chamber ion temperature
PARAMETER sim_tionCham  REAL 290.11375

D sim_tradCham Initial chamber radiation temperature
PARAMETER sim_tradCham  REAL 290.11375

D sim_eosCham chamber EOS type
PARAMETER sim_eosCham   STRING "eos_gam" ["eos_tab","eos_gam"]

D lase_variable saves (density of) the irradiated energy from EnergyDeposition unit, cf. RP ed_irradVarName
VARIABLE lase TYPE: PER_VOLUME
"""


class ConfigGenerator:
    """FLASH Config 文件生成器 (自包含)。

    从硬编码的默认模板生成 Config 内容。
    """

    def __init__(self):
        self.default_content = DEFAULT_CONFIG_CONTENT

    def generate(
        self,
        simulation_path: str = "hello/LaserSlab1d_new",
        target_material: Any = None,
        chamber_gas: Any = None,
        extra_datafiles: Optional[List[str]] = None,
        include_thomson: bool = False,
    ) -> str:
        """生成 Config 文件内容。

        Args:
            simulation_path: 仿真路径标识（用于注释）
            target_material: 靶材 Material 对象（预留，暂不处理）
            chamber_gas: 腔室气体 Material 对象（预留，暂不处理）
            extra_datafiles: 额外的 DATAFILES
            include_thomson: 是否包含 Thomson 散射诊断

        Returns:
            Config 文件内容字符串
        """
        content = self.default_content

        # 替换 DATAFILES 部分
        datafiles = set()
        if target_material is not None and hasattr(target_material, 'file'):
            datafiles.add(target_material.file)
        if chamber_gas is not None and hasattr(chamber_gas, 'file'):
            datafiles.add(chamber_gas.file)
        if datafiles:
            # 重建 content 中的 DATAFILES 行
            lines = content.split("\n")
            new_lines = []
            in_datafiles = False
            added_datafiles = False
            for line in lines:
                if line.startswith("DATAFILES"):
                    if not in_datafiles:
                        in_datafiles = True
                        for f in sorted(datafiles):
                            new_lines.append(f"DATAFILES {f}")
                        added_datafiles = True
                    continue
                elif in_datafiles and not line.startswith("DATAFILES"):
                    in_datafiles = False
                if not added_datafiles and in_datafiles:
                    continue
                new_lines.append(line)
            if not added_datafiles:
                # 插入 DATAFILES 行
                insert_idx = 0
                for i, line in enumerate(new_lines):
                    if "REQUIRES" in line:
                        insert_idx = i + 1
                datafile_lines = [f"DATAFILES {f}" for f in sorted(datafiles)]
                new_lines[insert_idx:insert_idx] = datafile_lines
            content = "\n".join(new_lines)

        if extra_datafiles:
            lines = content.split("\n")
            for f in extra_datafiles:
                lines.append(f"DATAFILES {f}")
            content = "\n".join(lines)

        if include_thomson:
            content += """

USESETUPVARS ThscDemo
IF ThscDemo
   REQUIRES diagnostics/ThomsonScattering
   VARIABLE pwin
   VARIABLE pwia
   VARIABLE pwde
   VARIABLE pwd1
   VARIABLE pwi2
   VARIABLE pwd2
ENDIF
"""

        return content

    def save(
        self,
        output_path: Union[str, Path],
        simulation_path: str = "hello/LaserSlab1d_new",
        target_material: Any = None,
        chamber_gas: Any = None,
        extra_datafiles: Optional[List[str]] = None,
        include_thomson: bool = False,
    ) -> Path:
        """生成并保存 Config 文件。"""
        content = self.generate(
            simulation_path=simulation_path,
            target_material=target_material,
            chamber_gas=chamber_gas,
            extra_datafiles=extra_datafiles,
            include_thomson=include_thomson,
        )
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content, encoding="utf-8")
        return out
